<?php

use Illuminate\Database\Seeder;

class LocalidadesTable_8_12_Seeder extends Seeder
{
	protected $localidades =[
     [ 'nombre' => '', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => '', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'A', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'ACHICO', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'AGRIO BALSA', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'AGUADA CHACAY CO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'AGUADA FLORENCIO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'AGUADA SAN ROQUE', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'AGUAS DE LAS MULAS', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'ALIANZA', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'ALICURA', 'codigo_postal' => 8403, 'id_provincia' => 15 ],
     [ 'nombre' => 'ALUMINE', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'ANDACOLLO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'ANQUINCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'ARROYITO', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'ARROYITO CHALLACO', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'ARROYO BLANCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'ARROYO CAHUNCO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'ARROYO QUILLEN', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'ARROYO RANQUILCO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'ATREUCO', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'AUCA MAHUIDA', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'AUCA PAN', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'BAJADA COLORADA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'BAJADA DE LOS MOLLES', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'BAJADA DEL AGRIO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'BAJADA DEL MARUCHO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'BALNEARIO DEL RIO AGRIO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'BALSA DEL RIO AGRIO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'BALSA SENILLOSA', 'codigo_postal' => 8316, 'id_provincia' => 15 ],
     [ 'nombre' => 'BARDA ANGUIL', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'BARDA NEGRA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'BARRANCAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'BATRE LAUQUEN', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'BELLA VISTA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'BUENA ESPERANZA', 'codigo_postal' => 8360, 'id_provincia' => 15 ],
     [ 'nombre' => 'BUTA CO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'BUTA MALLIN', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'BUTA RANQUIL', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'BUTALON', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAEPE MALAL', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAICHIHUE', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAJON DE ALMAZA', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAJON DE LOS PATOS', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAJON DE MANZANO', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAJON DEL TORO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAJON GRANDE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CALEUFU', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CALIHUE', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAMALEONES', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAMINERA', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAMINERA TRAFUL', 'codigo_postal' => 8403, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAMPAMENTO SOL', 'codigo_postal' => 8319, 'id_provincia' => 15 ],
     [ 'nombre' => 'CANCHA HUINGANCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CARRAN CURA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'CARRERI', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CARRI LAUQUEN', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'CARRI LIL', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'CASA DE PIEDRA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CATAN LIL', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAVIAHUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CAYANTA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CENTENARIO', 'codigo_postal' => 8309, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO COLORADO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO DE LA GRASA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO DE LA PARVA', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO DE LOS PINOS', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO DEL LEON', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO GATO', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO NEGRO CHAPUA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CERRO NEGRO TRICAO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHACABUCO', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHACAY', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHACAY CO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHACAY MELEHUE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHACAYCO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHACOYAL', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHALLACO', 'codigo_postal' => 8318, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHANQUIL QUILLA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHAPELCO', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHAPUA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHAPUA ABAJO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHARAHUILLA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHENQUECURA', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHICHIGUAY', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHIMEHUIN', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHINA MUERTA', 'codigo_postal' => 8316, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHINCHINA', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHIUQUILLIHUIN', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHOCHOY MALLIN', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHORRIACA', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'CHOS MALAL', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'COCHICO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CODIHUE', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'COIHUECO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'COLI MALAL', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'COLIPILI', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'COLLON CURA', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'COLLUN CO', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'CONFLUENCIA DEL AGUIJON', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'COPAHUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'CORRAL DE PIEDRA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CORRENTOSO', 'codigo_postal' => 8407, 'id_provincia' => 15 ],
     [ 'nombre' => 'COSTA DEL ARROYO SALADO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'COSTA LIMAY', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'COVUNCO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'COVUNCO ABAJO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'COVUNCO ARRIBA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'COVUNCO CENTRO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'COYUCO COCHICO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CUCHILLO CURA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'CULLIN MANZANO', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'CURA CO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CURU  LEUVU', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'CUTRAL CO', 'codigo_postal' => 8322, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL ALAMITO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL ARBOLITO', 'codigo_postal' => 8407, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL ATRAVESADO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL BOSQUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL CERRITO', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL CHINGUE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL CHOLAR', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL CURILEO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL DORMIDO', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL DURAZNO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL ESCORIAL', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL GATO', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL HUECU', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL MACHETE', 'codigo_postal' => 8407, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL MANZANO', 'codigo_postal' => 8403, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL OASIS', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL OVERO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL PALAO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL PERALITO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL PINO ANDINO', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL PORTON', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL PORVENIR', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL SALADO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL SALITRAL', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL SAUCE', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL TROMEN', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'EL TROPEZON', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'ESPINAZO DEL ZORRO', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'ESTANCIA LA PRIMAVERA', 'codigo_postal' => 8403, 'id_provincia' => 15 ],
     [ 'nombre' => 'ESTANCIA NEWBERY', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'ESTANCIA TEQUEL MALAL', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'FILMATUE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'FILO HUA HUM', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'FLORES', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'FORTIN 1 DE MAYO', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'FORTIN GUA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'FRANHUCURA', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'GENTE GRANDE', 'codigo_postal' => 8379, 'id_provincia' => 15 ],
     [ 'nombre' => 'GO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'GUA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'HAICHOL', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'HARAS PATRIA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'HAYCU', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUA HUM', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUALCUPEN', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUANTRAICO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUARACO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUARENCHENQUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUECHAHUE', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUECHULAFQUEN', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUILLILON', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUINCA LU', 'codigo_postal' => 8403, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUINGANCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUITRIN', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUMIGAMIO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'HUNCAL', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'INVERNADA VIEJA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'ISLA VICTORIA', 'codigo_postal' => 8400, 'id_provincia' => 15 ],
     [ 'nombre' => 'JECANASCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'JUARANCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'JUNIN DE LOS ANDES', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'KILCA CASA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ANGOSTURA DE ICALMA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ARAUCARIA', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ARBOLEDA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ARGENTINA', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ATALAYA', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA BUITRERA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA CIENAGA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA CIENEGUITA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ESTACADA', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA FORTUNA', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA FRIA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA ISABEL', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA LIPELA', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA NEGRA', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA OFELIA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA PATAGONIA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA PATRIA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA PICAZA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA PINTADA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA POCHOLA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA PORTE', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA PRIMAVERA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA RINCONADA', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA SALADA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA SUSANA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA TERESA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA TERESA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA UNION', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'LA VERDAD', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAGO ', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAGO LOLOG', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAGO PULMARI', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAGOTERA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAGUNA BLANCA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAGUNA MIRANDA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAJA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAPA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAPACHAL', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS ABEJAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS BANDURRIAS', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS BARDITAS', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS CHACRAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS COLORADAS', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS CORTADERAS', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS CORTADERAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS LAGUNAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS LAJAS', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS LAJITAS', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS MERCEDES', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS OVEJAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS PERLAS', 'codigo_postal' => 8300, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS SALADAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS TOSCAS', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LAS TRES LAGUNAS', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LASCAR', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'LEUTO CABALLO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LILEO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LIMAY CENTRO', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'LITRAN', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LIU CULLIN', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LLAMUCO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOLOG', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOMA DE LA LATA', 'codigo_postal' => 8300, 'id_provincia' => 15 ],
     [ 'nombre' => 'LONCO LUAN', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LONCO MULA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'LONCOPUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS BOLILLOS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS CARRIZOS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS CATUTOS', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS CHACALES', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS CHIHUIDOS', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS CHINITOS', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS CISNES', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS ENTIERROS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS GALPONES', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS MENUCOS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS MICHES', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS MOLLES', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS MUCHACHOS', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS RODILLOS', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS SAUCES', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'LOS TRES CHORROS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LUBECA', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'LUICOCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'LUIN COCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MACHICO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALALCO', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN BLANCO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN CHILENO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN DE LA CUEVA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN DE LAS YEGUAS', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN DE LOS CABALLOS', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN DE MENA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN DEL RUBIO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN DEL TORO', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'MALLIN QUEMADO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'MAMUL MALAL', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'MANZANO AMARGO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MARI MENUCO', 'codigo_postal' => 8300, 'id_provincia' => 15 ],
     [ 'nombre' => 'MARIANO MORENO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'MAYAN MAHUIDA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MEDIA LUNA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'MILLA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MINA CARRASCOSA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MINA LILEO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'MOQUEHUE', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'MULICHINCO', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'NAHUEL HUAPI', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'NAHUEL MAPE', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'NAHUEVE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'NALAY CULLIN', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'NAU NAUCO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'NERECO NORTE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'NEUQUEN', 'codigo_postal' => 8300, 'id_provincia' => 15 ],
     [ 'nombre' => 'NIRECO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'NOGUEIRA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'OCTAVIO PICO', 'codigo_postal' => 8319, 'id_provincia' => 15 ],
     [ 'nombre' => 'OJO DE AGUA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'OJO DE AGUA', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'PALAU', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'PALITUE', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'PAMPA COLLON CURA', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'PAMPA DE LONCO LUAN', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'PAMPA DE TRIL', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'PAMPA DEL MALLEO', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'PAMPA DEL SALADO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'PAMPA FERREIRA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'PANTANITOS', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO AGUERRE', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO ANCHO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO BARDA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO CATA TUN', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO COIHUE', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO DE LOS INDIOS', 'codigo_postal' => 8318, 'id_provincia' => 15 ],
     [ 'nombre' => 'PASO DE SAN IGNACIO', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'PE', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'PENINSULA HUEMUL', 'codigo_postal' => 8400, 'id_provincia' => 15 ],
     [ 'nombre' => 'PICHAIHUE', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'PICHE PONON', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PICHI NEUQUEN', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'PICUN LEUFU', 'codigo_postal' => 8313, 'id_provincia' => 15 ],
     [ 'nombre' => 'PIEDRA DEL AGUILA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'PIEDRA MALA', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'PIEDRA PINTADA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'PIEDRAS BAYAS', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PILMATUE', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'PILO LIL', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'PINO HACHADO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PINO SOLO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PLANICIE BANDERITA', 'codigo_postal' => 8301, 'id_provincia' => 15 ],
     [ 'nombre' => 'PLAZA HUINCUL', 'codigo_postal' => 8318, 'id_provincia' => 15 ],
     [ 'nombre' => 'PLOTTIER', 'codigo_postal' => 8316, 'id_provincia' => 15 ],
     [ 'nombre' => 'PORTADA COVUNCO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'PORTEZUELO GRANDE', 'codigo_postal' => 8300, 'id_provincia' => 15 ],
     [ 'nombre' => 'POZO HUALICHES', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PRIMEROS PINOS', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'PUEBLO NUEVO', 'codigo_postal' => 8322, 'id_provincia' => 15 ],
     [ 'nombre' => 'PUENTE PICUN LEUFU', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'PUERTO ANCHORENA', 'codigo_postal' => 8400, 'id_provincia' => 15 ],
     [ 'nombre' => 'PUERTO MANZANO', 'codigo_postal' => 8407, 'id_provincia' => 15 ],
     [ 'nombre' => 'PUESTO HERNANDEZ  BATERIAS', 'codigo_postal' => 8319, 'id_provincia' => 15 ],
     [ 'nombre' => 'PUNTA DE SIERRA', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUEBRADA HONDA', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUEMPU LEUFU', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUEMQUEMTREU', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUENTRENQUEN', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUILA QUEHUE', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUILA QUINA', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUILCA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUILI MALAL', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUILLEN', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUILQUIHUE', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUININELIU', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUINQUIMITREO', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUINTUCO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'QUITA QUINA', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'RAHUE', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'RAMICHAL', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'RAMON M CASTRO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'RANQUELES', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'RANQUIL VEGA', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'RANQUILCO', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'RANQUILON', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'RE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'RICHOIQUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'RINCON CHICO', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'RINCON DE EMILIO', 'codigo_postal' => 8300, 'id_provincia' => 15 ],
     [ 'nombre' => 'RINCON DE LOS SAUCES', 'codigo_postal' => 8319, 'id_provincia' => 15 ],
     [ 'nombre' => 'RINCON GRANDE', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'RIO AGRIO', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'RIO BARRANCAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'RUCA CHOROY ARRIBA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'SA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAINUCO', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'SALQUICO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN BERNARDO', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN DEMETRIO', 'codigo_postal' => 8347, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN EDUARDO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN IGNACIO', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN JUAN JUNIN DE LOS ANDES', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN JUAN RAHUE', 'codigo_postal' => 8341, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN MARTIN DE LOS ANDES', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAN PATRICIO DEL CHA', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'SANTA ISABEL', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'SANTA ISABEL', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'SANTA ISABEL', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'SANTA MARIA', 'codigo_postal' => 8401, 'id_provincia' => 15 ],
     [ 'nombre' => 'SANTO DOMINGO', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'SANTO TOMAS', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'SAUZAL BONITO', 'codigo_postal' => 8319, 'id_provincia' => 15 ],
     [ 'nombre' => 'SENILLOSA', 'codigo_postal' => 8316, 'id_provincia' => 15 ],
     [ 'nombre' => 'TAQUI NILEU', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'TAQUIMILAN', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'TAQUIMILLAN ABAJO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'TIERRAS BLANCAS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'TIHUE', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'TIPILIUKE', 'codigo_postal' => 8373, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRAHUNCURA', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRALAITUE', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRATAYEN', 'codigo_postal' => 8305, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRES CHORROS', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRES PICOS', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRES PIEDRAS', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRICAO MALAL', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'TRILI', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'TROMEN', 'codigo_postal' => 8371, 'id_provincia' => 15 ],
     [ 'nombre' => 'TROMPUL', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'VACA MUERTA', 'codigo_postal' => 8351, 'id_provincia' => 15 ],
     [ 'nombre' => 'VARVARCO', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA CURI LEUVU', 'codigo_postal' => 8353, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA EL CHOCON', 'codigo_postal' => 8311, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA LA ANGOSTURA', 'codigo_postal' => 8407, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA LAGO MELIQUINA', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA PEHUENIA', 'codigo_postal' => 8345, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA RAUR', 'codigo_postal' => 8370, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA RINCON CHICO', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILLA TRAFUL', 'codigo_postal' => 8403, 'id_provincia' => 15 ],
     [ 'nombre' => 'VILU MALLIN', 'codigo_postal' => 8349, 'id_provincia' => 15 ],
     [ 'nombre' => 'VISTA ALEGRE NORTE', 'codigo_postal' => 8309, 'id_provincia' => 15 ],
     [ 'nombre' => 'VISTA ALEGRE SUR', 'codigo_postal' => 8309, 'id_provincia' => 15 ],
     [ 'nombre' => 'ZAINA YEGUA', 'codigo_postal' => 8315, 'id_provincia' => 15 ],
     [ 'nombre' => 'ZAPALA', 'codigo_postal' => 8340, 'id_provincia' => 15 ],
     [ 'nombre' => 'ZINGONE Y CIA M', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => 'ZULEMITA', 'codigo_postal' => 8375, 'id_provincia' => 15 ],
     [ 'nombre' => '', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => '', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => '6 DE OCTUBRE', 'codigo_postal' => 8134, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUADA CECILIO', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUADA DE GUERRA', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUADA DE LOS PAJARITOS', 'codigo_postal' => 8301, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUADA DE PIEDRA', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUADA DEL LORO', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUADA GUZMAN', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'AGUARA', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'ALANITOS', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'ALLEN', 'codigo_postal' => 8328, 'id_provincia' => 16 ],
     [ 'nombre' => 'ANECON CHICO', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'ANECON GRANDE', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO BLANCO', 'codigo_postal' => 8403, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO CHACAY', 'codigo_postal' => 8401, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO DE LA VENTANA', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO LAS MINAS', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO LOS BERROS', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO SALADO', 'codigo_postal' => 8532, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO TEMBRADO', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'ARROYO VERDE', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'ATRAICO', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'BAJO DEL GUALICHO', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'BAJO RICO', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'BALNEARIO EL CONDOR', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'BALNEARIO LAS GRUTAS', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'BARDA COLORADA', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'BARDA DEL MEDIO', 'codigo_postal' => 8305, 'id_provincia' => 16 ],
     [ 'nombre' => 'BARRIL NIYEO', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'BARRIO LAGUNA', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'BARRIO NORTE', 'codigo_postal' => 8328, 'id_provincia' => 16 ],
     [ 'nombre' => 'BENJAMIN ZORRILLA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'BOCA DE LA TRAVESIA', 'codigo_postal' => 8505, 'id_provincia' => 16 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'CALTRAUNA', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'CAMPANA MAHUIDA', 'codigo_postal' => 8532, 'id_provincia' => 16 ],
     [ 'nombre' => 'CANLLEQUIN', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'CARHUE', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CARRI YEGUA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'CARRILAUQUEN', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'CASA QUEMADA', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CASCADA LOS CANTAROS', 'codigo_postal' => 8411, 'id_provincia' => 16 ],
     [ 'nombre' => 'CATRIEL', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'CERRO ABANICO', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'CERRO ALTO', 'codigo_postal' => 8403, 'id_provincia' => 16 ],
     [ 'nombre' => 'CERRO MESA', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'CERRO POLICIA', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'CERVANTES', 'codigo_postal' => 8326, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHACALHUA RUCA', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHACAY HUARRUCA', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHACRAS DE ALLEN', 'codigo_postal' => 8328, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHAIFUL', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHASICO', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHELFORO', 'codigo_postal' => 8366, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHENQUENIYEU', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHICHIHUAO', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHICHINALES', 'codigo_postal' => 8326, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHIMPAY', 'codigo_postal' => 8364, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHINA MUERTA', 'codigo_postal' => 8504, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHIPAUQUIL', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHOCORI', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHOELE CHOEL', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'CHURQUI', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CINCO CHA', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'CINCO SALTOS', 'codigo_postal' => 8303, 'id_provincia' => 16 ],
     [ 'nombre' => 'CIPOLLETTI', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'CLEMENTE ONELLI', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLAN CONHUE', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLI TORO', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA ALTE GUERRICO', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA EL MANZANO', 'codigo_postal' => 8305, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA GENERAL FRIAS', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA JOSEFA', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA JULIA Y ECHARREN', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA LA LUISA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA REGINA', 'codigo_postal' => 8336, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA RUSA', 'codigo_postal' => 8332, 'id_provincia' => 16 ],
     [ 'nombre' => 'COLONIA SAN JUAN', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'COMALLO', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'COMALLO ABAJO', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'COMI CO', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'CONA NIYEU', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'CONTRALMIRANTE CORDERO', 'codigo_postal' => 8301, 'id_provincia' => 16 ],
     [ 'nombre' => 'CONTRALMIRANTE M GUERRICO', 'codigo_postal' => 8328, 'id_provincia' => 16 ],
     [ 'nombre' => 'COQUELEN', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORONEL BELISLE', 'codigo_postal' => 8364, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORONEL EUGENIO DEL BUSTO', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORONEL FRANCISCO SOSA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORONEL JUAN JOSE GOMEZ', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORONEL VIDAL', 'codigo_postal' => 8305, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORRAL DE LOS PINOS', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CORRALITO', 'codigo_postal' => 8403, 'id_provincia' => 16 ],
     [ 'nombre' => 'COS ZAURES', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'COSTA DEL RIO AZUL', 'codigo_postal' => 8430, 'id_provincia' => 16 ],
     [ 'nombre' => 'COSTAS DEL PICHI LEUFU', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'CUATRO ESQUINAS', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'CUBANEA', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'CUENCA VIDAL', 'codigo_postal' => 8301, 'id_provincia' => 16 ],
     [ 'nombre' => 'CUESTA DEL TERNERO', 'codigo_postal' => 9210, 'id_provincia' => 16 ],
     [ 'nombre' => 'CURA LAUQUEN', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'DARWIN', 'codigo_postal' => 8364, 'id_provincia' => 16 ],
     [ 'nombre' => 'DINA HUAPI', 'codigo_postal' => 8402, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL BOLSON', 'codigo_postal' => 8430, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL CACIQUE', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL CAIN', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL CAMARURO', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL CHEIFUL', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL CONDOR ESTANCIA', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL CUY', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL DIQUE', 'codigo_postal' => 8500, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL FOYEL', 'codigo_postal' => 8401, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL GAUCHO POBRE', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL JARDINERO', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL MANSO', 'codigo_postal' => 8430, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL MANZANO', 'codigo_postal' => 8328, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL MOLIGUE', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL PANTANOSO', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL PORVENIR', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'EL SALADO', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'EMPALME KILOMETRO 648', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'ESTANCIA LAS JULIAS', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'FALCKNER', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'FERRI', 'codigo_postal' => 8301, 'id_provincia' => 16 ],
     [ 'nombre' => 'FITA RUIN', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'FITALANCAO', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'FITAMICHE', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'FITATIMEN', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'FORTIN UNO', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'GANZU LAUQUEN', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'GENERAL CONESA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'GENERAL ENRIQUE GODOY', 'codigo_postal' => 8336, 'id_provincia' => 16 ],
     [ 'nombre' => 'GENERAL FERNANDEZ ORO', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'GENERAL LIBORIO BERNAL', 'codigo_postal' => 8500, 'id_provincia' => 16 ],
     [ 'nombre' => 'GENERAL ROCA', 'codigo_postal' => 8332, 'id_provincia' => 16 ],
     [ 'nombre' => 'GUARDIA MITRE', 'codigo_postal' => 8505, 'id_provincia' => 16 ],
     [ 'nombre' => 'HUA MICHE', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'HUAN LUAN', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'INGENIERO HUERGO', 'codigo_postal' => 8334, 'id_provincia' => 16 ],
     [ 'nombre' => 'INGENIERO JACOBACCI', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'INGENIERO ZIMMERMANN RESTA', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'INGENIO SAN LORENZO', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'IRIS', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'ISLA CHICA', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'ISLA GRANDE', 'codigo_postal' => 8361, 'id_provincia' => 16 ],
     [ 'nombre' => 'JAG', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'JITA RUSIA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'JUAN DE GARAY', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'KILI MALAL', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'KILOMETRO 1218', 'codigo_postal' => 8305, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ALIANZA', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ANGOSTURA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA BOMBILLA', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA CAROLINA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA CHILENA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA CRIOLLITA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ELVIRA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA EMILIA', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ESMERALDA', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ESPERANZA', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ESTANCIA VIEJA', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA ESTRELLA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA EXCURRA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA FLECHA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA GRANJA', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA JULIA', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA LOBERIA', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA LUCINDA', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA MARIA INES', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA MESETA', 'codigo_postal' => 8500, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA MIMOSA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA PORTE', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA PRIMAVERA', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA QUEBRADA', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA RINCONADA', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA RUBIA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA SARA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'LA VENCEDORA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGO PELLEGRINI', 'codigo_postal' => 8305, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA BLANCA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA CORTES', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA DE LA PRUEBA', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA DEL BARRO', 'codigo_postal' => 8514, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA DEL MONTE', 'codigo_postal' => 8514, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA FRIAS', 'codigo_postal' => 8411, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNA LOS JUNCOS', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAGUNITA', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAMARQUE', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'LANQUI', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAS BAYAS', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAS MAQUINAS', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAS MELLIZAS', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LAS PIEDRAS', 'codigo_postal' => 8134, 'id_provincia' => 16 ],
     [ 'nombre' => 'LENZANIYEN', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOMA BLANCA', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'LONCO VACA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS COSTEROS', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS JUNCOS', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS MANANTIALES', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS MENUCOS', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS MOLINOS', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS PIRINEOS', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS QUEBRACHOS', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS REPOLLOS', 'codigo_postal' => 8430, 'id_provincia' => 16 ],
     [ 'nombre' => 'LOS SAUCES', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'LUIS BELTRAN', 'codigo_postal' => 8361, 'id_provincia' => 16 ],
     [ 'nombre' => 'LUIS M ZAGAGLIA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'MAINQUE', 'codigo_postal' => 8326, 'id_provincia' => 16 ],
     [ 'nombre' => 'MALLIN AHOGADO', 'codigo_postal' => 8430, 'id_provincia' => 16 ],
     [ 'nombre' => 'MAMUEL CHOIQUE', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'MANCHA BLANCA', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'MANCULLIQUE', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'MAQUINCHAO', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'MARIA CRISTINA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'MATA NEGRA', 'codigo_postal' => 8500, 'id_provincia' => 16 ],
     [ 'nombre' => 'MEDANOS NEGROS', 'codigo_postal' => 8134, 'id_provincia' => 16 ],
     [ 'nombre' => 'MENCUE', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'MENUCO VACA MUERTA', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'MICHI HONOCA', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'MICHIHUAO', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'MINISTRO RAMOS MEXIA', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'MULANILLO', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'MUSTERS', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'NAHUEL NIYEU', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'NAUPA HUEN', 'codigo_postal' => 8313, 'id_provincia' => 16 ],
     [ 'nombre' => 'NEGRO MUERTO', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'NENEO RUCA', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'NILUAN', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'NUEVA CAROLINA', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'NUEVO LEON', 'codigo_postal' => 8514, 'id_provincia' => 16 ],
     [ 'nombre' => 'OJOS DE AGUA EMBARCADERO FCGB', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'PADRE ALEJANDRO STEFANELLI', 'codigo_postal' => 8332, 'id_provincia' => 16 ],
     [ 'nombre' => 'PAJA ALTA', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'PALENQUE NIYEU', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'PANQUEHUAO', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO CHACABUCO', 'codigo_postal' => 8401, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO CORDOVA', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO DE LOS MOLLES', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO DEL LIMAY', 'codigo_postal' => 8403, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO FLORES', 'codigo_postal' => 8403, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO LEZCANO', 'codigo_postal' => 8361, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO MIRANDA', 'codigo_postal' => 8403, 'id_provincia' => 16 ],
     [ 'nombre' => 'PASO PIEDRA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'PE', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'PERCY H SCOTT', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'PERITO MORENO', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'PERITO MORENO ESTACION FCGR', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => 'PICHI LEUFU', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PICHI LEUFU ABAJO', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PICHI LEUFU ARRIBA', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PICHI MAHUIDA', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'PILAHUE', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'PILCANIYEU', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PILQUINIYEU', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'PILQUINIYEU DEL LIMAY', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'PLANICIE DE JAGUELITO', 'codigo_postal' => 8333, 'id_provincia' => 16 ],
     [ 'nombre' => 'PLAYA BONITA', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => 'POMONA', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'PORTEZUELO', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'POZO MORO', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'POZO SALADO', 'codigo_postal' => 8514, 'id_provincia' => 16 ],
     [ 'nombre' => 'PRAHUANIYEU', 'codigo_postal' => 8424, 'id_provincia' => 16 ],
     [ 'nombre' => 'PRIMERA ANGOSTURA', 'codigo_postal' => 8505, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUERTO BLEST', 'codigo_postal' => 8411, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUERTO OJO DE AGUA', 'codigo_postal' => 8409, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUERTO SAN ANTONIO ESTE', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUERTO TIGRE ISLA VICTORIA', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUESTO FARIA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUESTO GAVI', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'PUNTA DE AGUA', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'QUEMPU NIYEU', 'codigo_postal' => 8332, 'id_provincia' => 16 ],
     [ 'nombre' => 'QUETREQUILE', 'codigo_postal' => 8418, 'id_provincia' => 16 ],
     [ 'nombre' => 'QUINTA PANAL', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'RAYHUAO', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'REPOLLOS', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'RINCON DE GASTRE', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'RINCONADA', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'RIO CHICO', 'codigo_postal' => 8415, 'id_provincia' => 16 ],
     [ 'nombre' => 'RIO COLORADO', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'RIO SALADO', 'codigo_postal' => 8134, 'id_provincia' => 16 ],
     [ 'nombre' => 'RIO VILLEGAS', 'codigo_postal' => 8401, 'id_provincia' => 16 ],
     [ 'nombre' => 'RUCU LUAN', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'SACO VIEJO', 'codigo_postal' => 8514, 'id_provincia' => 16 ],
     [ 'nombre' => 'SALITRAL NEGRO', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN ANTONIO OESTE', 'codigo_postal' => 8520, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN CARLOS DE BARILOCHE', 'codigo_postal' => 8400, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN JAVIER', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN JORGE', 'codigo_postal' => 8324, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN JUAN', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN LEON', 'codigo_postal' => 8138, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN LORENZO', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN PEDRO', 'codigo_postal' => 8412, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN RAMON', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAN SIMON', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'SANTA ELENA', 'codigo_postal' => 8417, 'id_provincia' => 16 ],
     [ 'nombre' => 'SANTA GENOVEVA', 'codigo_postal' => 8363, 'id_provincia' => 16 ],
     [ 'nombre' => 'SANTA GREGORIA', 'codigo_postal' => 8364, 'id_provincia' => 16 ],
     [ 'nombre' => 'SANTA NICOLASA', 'codigo_postal' => 8364, 'id_provincia' => 16 ],
     [ 'nombre' => 'SARGENTO VIDAL', 'codigo_postal' => 8305, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAUCE BLANCO', 'codigo_postal' => 8360, 'id_provincia' => 16 ],
     [ 'nombre' => 'SAUCE BLANCO', 'codigo_postal' => 8505, 'id_provincia' => 16 ],
     [ 'nombre' => 'SEGUNDA ANGOSTURA', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'SIERRA COLORADA', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'SIERRA DE LA VENTANA', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'SIERRA GRANDE', 'codigo_postal' => 8532, 'id_provincia' => 16 ],
     [ 'nombre' => 'SIERRA PAILEMAN', 'codigo_postal' => 8521, 'id_provincia' => 16 ],
     [ 'nombre' => 'TENIENTE MAZA ESTACION FCGR', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'TERCERA ZONA', 'codigo_postal' => 8336, 'id_provincia' => 16 ],
     [ 'nombre' => 'TRAVESIA CASTRO', 'codigo_postal' => 8503, 'id_provincia' => 16 ],
     [ 'nombre' => 'TRENETA', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'TRES OJOS DE AGUAS', 'codigo_postal' => 8416, 'id_provincia' => 16 ],
     [ 'nombre' => 'TRICACO', 'codigo_postal' => 8332, 'id_provincia' => 16 ],
     [ 'nombre' => 'TROMENIYEU', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'TTE GRAL EUSTAQUIO FRIAS', 'codigo_postal' => 8501, 'id_provincia' => 16 ],
     [ 'nombre' => 'TUNQUELEN', 'codigo_postal' => 8409, 'id_provincia' => 16 ],
     [ 'nombre' => 'VACA LAUQUEN', 'codigo_postal' => 8422, 'id_provincia' => 16 ],
     [ 'nombre' => 'VALCHETA', 'codigo_postal' => 8536, 'id_provincia' => 16 ],
     [ 'nombre' => 'VALLE AZUL', 'codigo_postal' => 8336, 'id_provincia' => 16 ],
     [ 'nombre' => 'VALLE DE LOS ALAMOS', 'codigo_postal' => 8307, 'id_provincia' => 16 ],
     [ 'nombre' => 'VIEDMA', 'codigo_postal' => 8500, 'id_provincia' => 16 ],
     [ 'nombre' => 'VILLA ALBERDI', 'codigo_postal' => 8336, 'id_provincia' => 16 ],
     [ 'nombre' => 'VILLA LLANQUIN', 'codigo_postal' => 8401, 'id_provincia' => 16 ],
     [ 'nombre' => 'VILLA MANZANO', 'codigo_postal' => 8308, 'id_provincia' => 16 ],
     [ 'nombre' => 'VILLA MASCARDI', 'codigo_postal' => 8401, 'id_provincia' => 16 ],
     [ 'nombre' => 'VILLA REGINA', 'codigo_postal' => 8336, 'id_provincia' => 16 ],
     [ 'nombre' => 'VILLA TURISMO', 'codigo_postal' => 8430, 'id_provincia' => 16 ],
     [ 'nombre' => 'YAMINUE', 'codigo_postal' => 8534, 'id_provincia' => 16 ],
     [ 'nombre' => 'YUQUINCHE', 'codigo_postal' => 8418, 'id_provincia' => 16 ]
	];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('localidades')->insert($this->localidades);
    }
}
