<?php

use Illuminate\Database\Seeder;

class LocalidadesTable_6_12_Seeder extends Seeder
{
	protected $localidades =[
     [ 'nombre' => '25 DE MAYO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'ABRAMO', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'ADOLFO VAN PRAET', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'AGUA DE TORRE', 'codigo_postal' => 5621, 'provincia_id' => 11 ],
     [ 'nombre' => 'AGUAS BUENAS', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'AGUSTONI', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'ALFREDO PE', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'ALGARROBO DEL AGUILA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'ALPACHIRI', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'ALTA ITALIA', 'codigo_postal' => 6207, 'provincia_id' => 11 ],
     [ 'nombre' => 'ANGUIL', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'ANZOATEGUI', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'ARATA', 'codigo_postal' => 6385, 'provincia_id' => 11 ],
     [ 'nombre' => 'ARBOL DE LA ESPERANZA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'ARBOL SOLO', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'ARGENTINA BELVEDERE', 'codigo_postal' => 6367, 'provincia_id' => 11 ],
     [ 'nombre' => 'ARTURO ALMARAZ', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'ATALIVA ROCA', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'ATREUCO', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'AZTEAZU', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'BAJO DE LAS PALOMAS', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'BALO LOS MORROS', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'BARRANCAS COLORADAS', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'BARRANCAS COLORADAS', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'BARRIO EL MOLINO', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'BELGRANO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'BELLA VISTA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'BERNARDO LARROUDE', 'codigo_postal' => 6220, 'provincia_id' => 11 ],
     [ 'nombre' => 'BERNASCONI', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'BOEUF', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'BOLICHE LA ARA', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'BUTALO', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'CACHIRULO', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAICHUE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAIMI', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'CALCHAHUE', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'CALEU CALEU', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'CALEUFU', 'codigo_postal' => 6387, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO CARETTO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO CICARE', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO DE LOS TOROS', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO DE SALAS', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO LA FLORIDA', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO LUDUE', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO MOISES SECCION 1A', 'codigo_postal' => 6383, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO NICHOLSON', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO PICO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO SALUSSO', 'codigo_postal' => 6369, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAMPO URDANIZ', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'CARAMAN', 'codigo_postal' => 6387, 'provincia_id' => 11 ],
     [ 'nombre' => 'CARLOS BERG', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'CARRO QUEMADO', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'CASA DE PIEDRA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CATRILO', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'CAYUPAN', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'CEBALLOS', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'CEREALES', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'CERRO AZUL', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CERRO BAYO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CERRO DEL AIGRE', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CERRO LA BOTA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHACHARRAMENDI', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHACRA 16', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHACRA LA CASILDA', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHACRA LA MAGDALENA', 'codigo_postal' => 6621, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHACRAS DE VICTORICA', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHACU', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHAMAICO', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHANILAO', 'codigo_postal' => 6201, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHAPALCO', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'CHICALCO', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA 17 DE AGOSTO', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA AGUIRRE', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA ANASAGASTI', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA BARON', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA BEATRIZ', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA BEAUFORT', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA CAZAUX', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA CHICA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA DENEVI', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA DEVOTO', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA ECHETA', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA EL DESTINO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA EL PORVENIR', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA EL SAUZAL', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA EL TIGRE', 'codigo_postal' => 6385, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA ESPA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA ESPIGA DE ORO', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA FERRARO', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA GIUSTI', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA GOBERNADOR AYALA', 'codigo_postal' => 8307, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA GUIBURG N 2', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA HELVECIA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA ABUNDANCIA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA AMARGA', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA CARLOTA', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA CHISPA', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA ESPERANZA', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA GAVIOTA', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA INDIA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA MARGARITA', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA MUTUA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA ORACION', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA PASTORIL', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA PAZ', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LA SARA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LAGOS', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LAS MERCEDES', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LAS PIEDRITAS', 'codigo_postal' => 6385, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LAS TRES PIEDRAS', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LAS VIZCACHERAS', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LIA Y ALLENDE', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LOS PIOJOS', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LOS TOROS', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA LUNA', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA MARIA LUISA', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA MEDANO COLORADO', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA MIGLIORI', 'codigo_postal' => 6367, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA MINISTRO LOBOS', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA RAMON QUINTAS', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA ROCA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN BASILIO', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN FELIPE', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN IGNACIO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN JOSE', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN JUAN', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN LORENZO', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN MIGUEL', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN ROSARIO', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SAN VICTORIO', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA ANA', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA CECILIA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA CLARA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA ELENA', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA ELVIRA', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA MARIA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SANTA TERESA', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA SOBADELL', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA TORELLO', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA TRENQUENDA', 'codigo_postal' => 6220, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA TREQUEN', 'codigo_postal' => 6220, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA VASCONGADA', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIA VILLA ALBA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIAS DRYSDALE', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'COLONIAS MURRAY', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'CONA LAUQUEN', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'CONHELO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'CORONEL HILARIO LAGOS', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'COSTA DEL SALADO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'COTITA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'CUCHILLO CO', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'CURILCO', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'CURRU MAHUIDA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'DOBLAS', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'DORILA', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'DOS AMIGOS', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'DOS AMIGOS', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'DOS CHA', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'DOS DE IPI', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'DOS VIOLETAS', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'EDUARDO CASTEX', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL AGUILA', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL ANTOJO', 'codigo_postal' => 6220, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL BELGICA', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL BOQUERON', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL BRILLANTE', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL CARANCHO', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL CENTENARIO', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL CENTINELA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL CHILLEN', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL CINCO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESCANSO', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESCANSO  LONQUIMAY', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESLINDE', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESTINO', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESTINO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESTINO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DESTINO  ROLON', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DIEZ', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DIEZ Y SIETE', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL DURAZNO', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL ESCABEL', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL EUCALIPTO', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL EUCALIPTO CARRO QUEMADO', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL FURLONG', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL GUAICURU', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL GUANACO', 'codigo_postal' => 6205, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL GUANACO', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL GUANACO', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL HUITRU', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL LUCERO', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL MADRIGAL', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL MALACATE', 'codigo_postal' => 6341, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL MATE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL MIRADOR', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL MIRADOR DE JUAREZ', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL NUEVE', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL OASIS', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL ODRE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL OLIVO', 'codigo_postal' => 6203, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PALOMAR', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PARQUE', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PELUDO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PIMIA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PORVENIR', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PORVENIR', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL PUMA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL RECREO', 'codigo_postal' => 6220, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL REFUGIO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL RETIRO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL RUBI', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL SALITRAL', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL SAUCE', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL SILENCIO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TAJAMAR', 'codigo_postal' => 6205, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TARTAGAL', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TIGRE', 'codigo_postal' => 6203, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TORDILLO', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TRECE', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TRIGO', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL TRIUNFO', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL UNO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL VASQUITO', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL VERANEO', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'EL VOLANTE', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'EMBAJADOR MARTINI', 'codigo_postal' => 6203, 'provincia_id' => 11 ],
     [ 'nombre' => 'EMILIO MITRE', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'EPU PEL', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'ESTABLECIMIENTO EL CENTINELA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'ESTANCIA LA LUCHA', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'ESTANCIA LA PAMPEANA', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'ESTANCIA LA VOLUNTAD', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'EUSKADI', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'EX ESCUELA HOGAR NRO 5', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'FALUCHO', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'GALLINAO', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'GAVIOTAS', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'GENERAL ACHA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'GENERAL PICO', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'GENERAL SAN MARTIN', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'GERVASIO ORTIZ DE ROSAS', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'GOBERNADOR AYALA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'GOBERNADOR DUVAL', 'codigo_postal' => 8336, 'provincia_id' => 11 ],
     [ 'nombre' => 'GRAL MANUEL CAMPOS', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'GUADALOZA', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'GUARACO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'GUATRACHE', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'HIDALGO', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'HIPOLITO YRIGOYEN', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'HUCAL', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'HUELEN', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'INES Y CARLOTA', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'INGENIERO FOSTER', 'codigo_postal' => 6385, 'provincia_id' => 11 ],
     [ 'nombre' => 'INGENIERO LUIGGI', 'codigo_postal' => 6205, 'provincia_id' => 11 ],
     [ 'nombre' => 'INTENDENTE ALVEAR', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'IPI', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'IVANOWSKY', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'JACINTO ARAUZ', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'JAGUEL DEL ESQUINERO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'JAGUEL DEL MONTE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'JARDON', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'JULIAN A MANSILLA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'JUZGADO VIEJO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'KILOMETRO 619', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ADELA', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ADMINISTRACION', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ANTONIA', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ARA', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ASTURIANA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ATALAYA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA AURORA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA AVANZADA', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BANDERITA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BARRANCOSA', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BAYA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BAYA MUERTA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BILBAINA', 'codigo_postal' => 6345, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BLANCA', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA BOTA', 'codigo_postal' => 8307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CARMEN', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CAROLA', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CASILDA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CATALINA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CATALINA', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CATALINITA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CATITA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CAUTIVA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CELIA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CELINA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CELINA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CELMIRA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CHAPELLE', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CHIRLANDIA', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CHITA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CHITA PUELCHES', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CIENAGA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CLELIA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA COLORADA CHICA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA COLORADA GRANDE', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CONSTANCIA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CONSTANCIA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CONSTANCIA  ANGUIL', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA COPELINA', 'codigo_postal' => 8307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA CUMBRE', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA DELFINA', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA DELICIA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA DOLORES', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELENITA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELIA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELINA', 'codigo_postal' => 6203, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELINA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELSA', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELVA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ELVIRA', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ENERGIA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ENRIQUETA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESCONDIDA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESMERALDA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESMERALDA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESMERALDA MACACHIN', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESPERANZA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESPERANZA', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESPERANZA ANGUIL', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESPERANZA HIDALGO', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESPERANZA MACACHIN', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESPERANZA VERTIZ', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESTHER', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESTRELLA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ESTRELLA DEL SUD', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA EULOGIA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA FE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA FLORENCIA', 'codigo_postal' => 6317, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA FLORIDA', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA FORTUNA', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA GAVENITA', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA GAVIOTA', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA GLORIA', 'codigo_postal' => 6348, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA GUADALOSA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA GUE', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA HUMADA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA IMARRA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA INVERNADA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ISABEL', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ISABEL', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA JAPONESA', 'codigo_postal' => 8336, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA JOSEFINA', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA JUANITA', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA JUANITA', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA JUANITA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LAURENTINA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LE', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LIMPIA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LONJA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LUCHA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LUCHA LA REFORMA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LUISA', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA LUZ', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MAGDALENA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MAGDALENA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MALVINA', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MANUELITA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARCELA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARGARITA', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIA', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIA ELENA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIA ELISA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIA ROSA', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIA VERTIZ', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARIANITA', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MARUJA', 'codigo_postal' => 6385, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MATILDE', 'codigo_postal' => 6341, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MODERNA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA MOROCHA', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA NILDA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA NUEVA', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA NUEVA PROVINCIA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA OLLA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ORACION', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PALOMA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PAMPEANA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PAMPITA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PAMPITA HIDALGO', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PASTORIL', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PAULINA', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PAZ', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PENCOSA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PERLA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PERLITA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PIEDAD', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA POMONA', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PORTE', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PRADERA', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PRIMAVERA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PRIMAVERA CHAMAICO', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PRIMAVERA MIGUEL RIGLOS', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PRIMAVERA SANTA ROSA', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PRIMERA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PU', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PUMA', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PUMA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA PUNA', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA RAZON', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA RAZON SANTA ISABEL', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA REBECA', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA REFORMA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA REFORMA VIEJA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA RESERVA ANGUIL', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA RESERVA IVANOWSKY', 'codigo_postal' => 6341, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ROSA', 'codigo_postal' => 8133, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA SARITA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA SEGUNDA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA SIN NOMBRE', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA SOLEDAD', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA SORPRESA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA SUERTE', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA TERESITA', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA TINAJERA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA TORERA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA TOSCA', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA TRINIDAD', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA UNIDA', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA UNION', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA UNION', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VANGUARDIA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VEINTITRES', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VERDE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VERDE', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VERDE ANGUIL', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VICTORIA', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VICTORIA', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VICTORIA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VIOLETA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA VOLUNTAD', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'LA ZOTA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LABAL', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAGUNA QUIROGA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS ACACIAS', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS CHACRAS', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS DELICIAS', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS DELICIAS', 'codigo_postal' => 6221, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS DOS NACIONES', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS FELICITAS', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS GAVIOTAS', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS MALVINAS', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS PIEDRITAS', 'codigo_postal' => 6387, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS QUINTAS', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'LAS TRES HERMANAS', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'LEGASA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LEONA REDONDA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LIHUE CALEL', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LIMAY MAHUIDA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'LINDO VER', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOMA REDONDA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOMAS DE GATICA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOMAS OMBU', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LONQUIMAY', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOO CO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS ALAMOS', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS ALGARROBOS', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS DOS HERMANOS', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS MANANTIALES', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS MORROS', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS NOGALES', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS OLIVOS', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS PIRINEOS', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS QUINIENTOS', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS TAJAMARES', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS TOROS', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS TRES POZOS', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOS TURCOS', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 10', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 11', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 11 BERNASCONI', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 11 ESCUELA 107', 'codigo_postal' => 6213, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 12', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 12', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 12', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 13', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 13 ESCUELA 173', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 14', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 15', 'codigo_postal' => 6213, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 15 ESCUELA 18', 'codigo_postal' => 6387, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 17', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 17 ESCUELA 121', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 17 ESCUELA 95', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 18', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 18', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 18 ESCUELA 158', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 19', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 19  COLONIA N LEVEN', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 2 ESCUELA 185', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 2 LA ELINA', 'codigo_postal' => 6203, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 20', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 20 LA CARLOTA', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 21', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 21 COLONIA SANTA ELENA', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 22', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 22', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 22 IPI', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 23', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 23 ESCUELA 221', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 23 ESCUELA 264', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 24', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 24 SECCION 1A', 'codigo_postal' => 6383, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 25 CONHELO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 25 ESCUELA 146', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 25 ESCUELA 178', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 3', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 4', 'codigo_postal' => 6387, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 5 CALEUFU  ESC 120', 'codigo_postal' => 6205, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 5 LUAN TORO', 'codigo_postal' => 6317, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 6', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 6 ESCUELA 171', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 7', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 7 ESCUELA 270', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 8', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 8', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 8  ESCUELA 179', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 8 ESCUELA 141', 'codigo_postal' => 6369, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 8 ESCUELA 179', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 8 ESCUELA 184', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOTE 9 ESCUELA 140', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'LOVENTUEL', 'codigo_postal' => 6317, 'provincia_id' => 11 ],
     [ 'nombre' => 'LUAN TORO', 'codigo_postal' => 6317, 'provincia_id' => 11 ],
     [ 'nombre' => 'LUNA', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'MACACHIN', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'MAISONNAVE', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'MALVINAS ARGENTINAS', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'MANANTIALES', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'MARACO', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'MARACO CHICO', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'MARI MARI', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'MARIA', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'MARIANO MIRO', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'MAURICIO MAYER', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'MAYACO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'MEDANO BLANCO', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'MEDANO COLORADO', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'MEDANOS NEGROS', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'METILEO', 'codigo_postal' => 6367, 'provincia_id' => 11 ],
     [ 'nombre' => 'MIGUEL CANE', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'MIGUEL RIGLOS', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'MINAS DE SAL', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'MINERALES DE LA PAMPA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'MINISTRO ORLANDO', 'codigo_postal' => 6367, 'provincia_id' => 11 ],
     [ 'nombre' => 'MOCOVI', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'MONTE NIEVAS', 'codigo_postal' => 6383, 'provincia_id' => 11 ],
     [ 'nombre' => 'MONTE RALO', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'NAHUEL NAPA', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'NAICO', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'NANQUEL HUITRE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'NARCISO LEVEN', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'NERRE CO', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'NICOLAS VERA', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => 'OFICIAL E SEGURA', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'OJEDA', 'codigo_postal' => 6207, 'provincia_id' => 11 ],
     [ 'nombre' => 'OJO DE AGUA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'PARERA', 'codigo_postal' => 6213, 'provincia_id' => 11 ],
     [ 'nombre' => 'PARQUE LURO', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'PASO DE LOS ALGARROBOS', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'PASO DE LOS PUNTANOS', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'PASO LA BALSA', 'codigo_postal' => 8307, 'provincia_id' => 11 ],
     [ 'nombre' => 'PASO LA RAZON', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'PAVON', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'PERU', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'PICHE CONA LAUQUEN', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'PICHI HUILCO', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'PICHI HUINCA', 'codigo_postal' => 6385, 'provincia_id' => 11 ],
     [ 'nombre' => 'PICHI MAHUIDA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'PICHI MERICO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'POITAGUE', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'PUEBLO ALASSA', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'PUEBLO QUINTANA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'PUELCHES', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'PUELEN', 'codigo_postal' => 8307, 'provincia_id' => 11 ],
     [ 'nombre' => 'QUEHUE', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'QUEMU QUEMU', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'QUETREQUEN', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'QUI', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'QUINTANA', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'RAMON QUINTAS', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'RAMON SEGUNDO', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'RANCUL', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'REALICO', 'codigo_postal' => 6200, 'provincia_id' => 11 ],
     [ 'nombre' => 'RELMO', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'REMECO', 'codigo_postal' => 6311, 'provincia_id' => 11 ],
     [ 'nombre' => 'REMECO', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'RICARDO LAVALLE', 'codigo_postal' => 6312, 'provincia_id' => 11 ],
     [ 'nombre' => 'ROLON', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'RUCAHUE', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'RUCANELO', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'SALINAS', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'SALINAS GRANDES  ANZOATEGUI', 'codigo_postal' => 8138, 'provincia_id' => 11 ],
     [ 'nombre' => 'SALINAS GRANDES HIDALGO', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'SALINAS MARI MANUEL', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN ALBERTO', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN ANDRES', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN ANTONIO', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN AQUILINO', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN BASILIO', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN BENITO', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN BERNARDO', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN CARLOS', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN DIEGO', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN EDUARDO', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN EMILIO', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN ERNESTO', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN FELIPE', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN FERNANDO', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN FRANCISCO', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN FRANCISCO DE LA RAMADA', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN HILARIO', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN HUMBERTO', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN IGNACIO', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN ILDEFONSO', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOAQUIN', 'codigo_postal' => 6341, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOAQUIN', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOAQUIN METILEO', 'codigo_postal' => 6367, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 8204, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JOSE  ANGUIL', 'codigo_postal' => 6326, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JUAN', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JUAN', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JUAN SIMSON', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN JUSTO', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN MANUEL', 'codigo_postal' => 6352, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN MARCELO', 'codigo_postal' => 6214, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN MIGUEL', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN MIGUEL', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN PEDRO', 'codigo_postal' => 6330, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN PEDRO ROLON', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN RAMON', 'codigo_postal' => 6383, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN ROBERTO', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN SALVADOR', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN SIMON', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'SAN URBANO', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA ANA', 'codigo_postal' => 6309, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA AURELIA', 'codigo_postal' => 6239, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA CATALINA', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA CLARA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA ELENA', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA ELENA', 'codigo_postal' => 8201, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA ELVIRA', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA FELICITAS', 'codigo_postal' => 6220, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA GRACIA', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA INES', 'codigo_postal' => 6360, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA ISABEL', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA MARIA', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA ROSA', 'codigo_postal' => 6300, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTA STELLA', 'codigo_postal' => 6305, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTIAGO ORELLANO', 'codigo_postal' => 6325, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTO DOMINGO', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'SANTO TOMAS', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'SARAH', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'SECCION PRIMERA CONHELLO', 'codigo_postal' => 6383, 'provincia_id' => 11 ],
     [ 'nombre' => 'SIERRAS DE LIHUEL CALEL', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'SOL DE MAYO', 'codigo_postal' => 6333, 'provincia_id' => 11 ],
     [ 'nombre' => 'SPELUZZI', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'TA HUILCO', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'TELEN', 'codigo_postal' => 6321, 'provincia_id' => 11 ],
     [ 'nombre' => 'TOAY', 'codigo_postal' => 6303, 'provincia_id' => 11 ],
     [ 'nombre' => 'TOMAS M DE ANCHORENA', 'codigo_postal' => 6301, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRAICO', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRAICO GRANDE', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'TREBOLARES', 'codigo_postal' => 6361, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRENEL', 'codigo_postal' => 6369, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRES BOTONES', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRES HERMANOS MACACHIN', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRES HERMANOS QUETREQUEN', 'codigo_postal' => 6212, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRES LAGUNAS', 'codigo_postal' => 6228, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRES NACIONES', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRIBULUCI', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRILI', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'TRUBULUCO', 'codigo_postal' => 8212, 'provincia_id' => 11 ],
     [ 'nombre' => 'TTE GRAL EMILIO MITRE', 'codigo_postal' => 6381, 'provincia_id' => 11 ],
     [ 'nombre' => 'UNANUE', 'codigo_postal' => 8214, 'provincia_id' => 11 ],
     [ 'nombre' => 'URIBURU', 'codigo_postal' => 6354, 'provincia_id' => 11 ],
     [ 'nombre' => 'UTRACAN', 'codigo_postal' => 8203, 'provincia_id' => 11 ],
     [ 'nombre' => 'VALLE ARGENTINO', 'codigo_postal' => 6307, 'provincia_id' => 11 ],
     [ 'nombre' => 'VALLE ARGENTINO', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'VALLE DAZA', 'codigo_postal' => 8200, 'provincia_id' => 11 ],
     [ 'nombre' => 'VERTIZ', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'VICTORICA', 'codigo_postal' => 6319, 'provincia_id' => 11 ],
     [ 'nombre' => 'VILLA ALBA', 'codigo_postal' => 8206, 'provincia_id' => 11 ],
     [ 'nombre' => 'VILLA MENCUELLE', 'codigo_postal' => 8208, 'provincia_id' => 11 ],
     [ 'nombre' => 'VILLA MIRASOL', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'VILLA SAN JOSE', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'VISTA ALEGRE', 'codigo_postal' => 6323, 'provincia_id' => 11 ],
     [ 'nombre' => 'WINIFREDA', 'codigo_postal' => 6313, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA RURAL', 'codigo_postal' => 6331, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA RURAL', 'codigo_postal' => 6369, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA RURAL  METILEO', 'codigo_postal' => 6367, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA RURAL DE MIRASOL', 'codigo_postal' => 6315, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA RURAL DE VERTIZ', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA RURAL DORILA', 'codigo_postal' => 6365, 'provincia_id' => 11 ],
     [ 'nombre' => 'ZONA URBANA NORTE', 'codigo_postal' => 6380, 'provincia_id' => 11 ],
     [ 'nombre' => '', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'ABRA VERDE', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUA BLANCA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUA BLANCA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUA COLORADA', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUA COLORADA', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUA DE LA PIEDRA', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUA DE PIEDRA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUADA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUADITA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'AGUAYO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'AICU', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'AIMOGASTA', 'codigo_postal' => 5310, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALCAZAR', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALGARROBO GRANDE', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALPASINCHE', 'codigo_postal' => 5325, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALTILLO DEL MEDIO', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALTO BAYO', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALTO CARRIZAL', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'ALTO JAGUEL', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'AMANA', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'AMBIL', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'AMILGANCHO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'AMINGA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'AMPATA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'AMUSCHINA', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANCHICO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANCHUMBIL', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANDOLUCAS', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANGUINAN', 'codigo_postal' => 5363, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANGULOS', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANILLACO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANJULLON', 'codigo_postal' => 5303, 'provincia_id' => 12 ],
     [ 'nombre' => 'ANTINACO', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'ARAUCO', 'codigo_postal' => 5311, 'provincia_id' => 12 ],
     [ 'nombre' => 'ATILES', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'BA', 'codigo_postal' => 5310, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAJO CORRAL DE ISAAC', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAJO DE GALLO', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAJO GRANDE', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAJO HONDO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAJO HONDO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAJO JAGUEL', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'BALDE DEL QUEBRACHO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'BALDE SALADO', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'BALDE SALADO', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'BALDE SAN ISIDRO', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'BALDES DE PACHECO', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'BANDA FLORIDA', 'codigo_postal' => 5351, 'provincia_id' => 12 ],
     [ 'nombre' => 'BARRANQUITAS', 'codigo_postal' => 5474, 'provincia_id' => 12 ],
     [ 'nombre' => 'BARRIO DE GALLI', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAYO MUERTO', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'BAZAN', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'BELLA VISTA', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'BOCA DE LA QUEBRADA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'BUENA VISTA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'CA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'CACHIYUYAL', 'codigo_postal' => 5367, 'provincia_id' => 12 ],
     [ 'nombre' => 'CAMPANAS', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'CAMPO TRES POZOS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'CAPIHUAS', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'CARRIZAL', 'codigo_postal' => 5306, 'provincia_id' => 12 ],
     [ 'nombre' => 'CARRIZAL', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'CARRIZAL ESTACION FCGB', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'CARRIZALILLO', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'CARRIZALILLO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'CASA PINTADA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'CASAGATE', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'CASANGATE', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'CASAS VIEJAS', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'CASTRO BARROS', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'CATINZACO', 'codigo_postal' => 5374, 'provincia_id' => 12 ],
     [ 'nombre' => 'CATINZACO EMBARCADERO FCGB', 'codigo_postal' => 5374, 'provincia_id' => 12 ],
     [ 'nombre' => 'CATUNA', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'CEBOLLAR', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'CERRO NEGRO', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHA', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHAMICAL', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHAUPIHUASI', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHELCOS', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHEPES', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHEPES VIEJOS', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHILA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHILECITO', 'codigo_postal' => 5360, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHIMENEA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHULO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHUMBICHA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'CHUQUIS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'CISCO', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'COLONIA ALFREDO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'COLONIA ORTIZ DE OCAMPO', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'COMANDANTE LEAL', 'codigo_postal' => 5272, 'provincia_id' => 12 ],
     [ 'nombre' => 'CORDOBITA', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'CORRAL DE ISAAC', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'CORTADERAS', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'CORTADERAS EMBARCADERO FCGB', 'codigo_postal' => 5474, 'provincia_id' => 12 ],
     [ 'nombre' => 'CUATRO ESQUINAS', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'CUATRO ESQUINAS', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'CUEVA DEL CHACHO', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'CUIPAN', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'DESIDERIO TELLO', 'codigo_postal' => 5474, 'provincia_id' => 12 ],
     [ 'nombre' => 'DIQUE DE ANZULON', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'DIQUE LOS SAUCES', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'DIQUE LOS SAUCES', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'DISTRITO PUEBLO', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ABRA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ALTILLO', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ALTO', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ALTO', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BALDE', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BARRANCO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BARREAL', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BARRIAL', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BARRIAL', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BAYITO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL BORDO', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CALDEN', 'codigo_postal' => 5717, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CANTADERO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CARRIZAL', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CARRIZAL TAMA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CATORCE', 'codigo_postal' => 5474, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CERCO', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CHIFLON', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CHOCOY', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CHUSCHIN', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CHUSCO', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CIENAGO', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CINCUENTA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CONDADO', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL CONSUELO', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL DIVISADERO', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL DURAZNILLO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ESCONDIDO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ESTANQUITO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL FRAILE', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL FUERTE', 'codigo_postal' => 5351, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL GARABATO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL HORNO', 'codigo_postal' => 5357, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL HUACO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL JUMEAL', 'codigo_postal' => 5365, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL MEDANITO', 'codigo_postal' => 5272, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL MEDANO', 'codigo_postal' => 5263, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL MOLLAR', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL MOLLE', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL PEDREGAL', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL PLUMERILLO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL PORTEZUELO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL POTRERILLO', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL POTRERILLO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL POTRERILLO', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL POTRERILLO R V PE', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL POTRERO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL PUEBLITO', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL PUESTO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL QUEBRACHAL', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL QUEBRACHO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL QUEBRACHO', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL QUEMADO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL QUEMADO', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL RETAMAL', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL RETAMO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL RETIRO', 'codigo_postal' => 5325, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL RODEO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ROSARIO', 'codigo_postal' => 5263, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL TALA', 'codigo_postal' => 5304, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL TALA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL VALDECITO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL VALLE', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL VALLECITO', 'codigo_postal' => 5360, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL VERDE', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'EL ZAPALLAR', 'codigo_postal' => 5353, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESPERANZA DE LOS CERRILLOS', 'codigo_postal' => 5263, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESQUINA DEL NORTE', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESQUINA DEL SUD', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESQUINA GRANDE', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESTACION 69', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESTACION MAZAN', 'codigo_postal' => 5313, 'provincia_id' => 12 ],
     [ 'nombre' => 'ESTANCIA DE MAIZ', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'FALDA DE CITAN', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'FAMATINA', 'codigo_postal' => 5365, 'provincia_id' => 12 ],
     [ 'nombre' => 'FLAMENCO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'FRANCISCO ORTIZ DE OCAMPO', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'GOBERNADOR GORDILLO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'GUACHIN', 'codigo_postal' => 5367, 'provincia_id' => 12 ],
     [ 'nombre' => 'GUANDACOL', 'codigo_postal' => 5353, 'provincia_id' => 12 ],
     [ 'nombre' => 'GUAYAPA', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'HUACO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'HUAJA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'HUNQUILLAL', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'ILIAR', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'ILISCO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'ILLISCA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'ISMIANGO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'JAGUE', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'JESUS MARIA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 619', 'codigo_postal' => 5272, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 645', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 682', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 732', 'codigo_postal' => 5717, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 861', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 875', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 891', 'codigo_postal' => 5313, 'provincia_id' => 12 ],
     [ 'nombre' => 'KILOMETRO 921', 'codigo_postal' => 5313, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA AGUADA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA AGUADITA', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA AGUADITA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA AMERICA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ANTIGUA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ARMONIA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA BANDA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA BANDA', 'codigo_postal' => 5365, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA BUENA ESTRELLA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA BUENA SUERTE', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CALERA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CALLANA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CARRIZANA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CHILCA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CHIMENEA', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CIENAGA', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CIENAGA', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CONSULTA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA CUADRA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA DORA', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ENVIDIA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ESCONDIDA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ESPERANZA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ESQUINA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ESQUINA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA FLOR', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA FLORIDA', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA HIGUERA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA HUERTA', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA IGUALDAD', 'codigo_postal' => 5474, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA INVERNADA', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ISLA', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA JARILLA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA LAGUNA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA LANCHA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA LATA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA LIBERTAD', 'codigo_postal' => 5263, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA LIBERTAD', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA LOMITA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA MARAVILLA', 'codigo_postal' => 5351, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA MERCED', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PAMPA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PAMPA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PERLITA', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PINTADA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PIRGUA', 'codigo_postal' => 5325, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PLAZA', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PRIMAVERA', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA PUNTILLA', 'codigo_postal' => 5367, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA RAMADITA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA REFORMA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA REPRESA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA REPRESA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA RIOJA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA ROSILLA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA SERENA', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA TORDILLA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA TORRE', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA TRAMPA', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'LA YESERA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS AGUADITAS', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS BARRANCAS', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS BOMBAS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS CA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS CATAS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS GREDAS', 'codigo_postal' => 5365, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS HIGUERAS', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS HIGUERILLAS', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS PADERCITAS', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS PADERCITAS', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS PALOMAS', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS PE', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS SALINAS', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS SIERRAS BRAVAS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS TALAS', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS TOSCAS', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS TUCUMANESAS', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS TUSCAS', 'codigo_postal' => 5310, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS TUSCAS', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LAS VERTIENTES', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOMA BLANCA', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOMA LARGA', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOMA LARGA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOROHUASI', 'codigo_postal' => 5325, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS AGUIRRES', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS ALANICES', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS ALGARROBOS', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS BALDECITOS', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS BALDES', 'codigo_postal' => 5310, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS BARRIACITOS', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS BARRIALITOS', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS BORDOS', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS CERRILLOS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS COLORADOS', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS CORIAS', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS CORRALES', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS FRANCES', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS MISTOLES', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS MOGOTES COLORADOS', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS MOLINOS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS NACIMIENTOS', 'codigo_postal' => 5353, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS OLIVARES', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS OLMOS', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS OROS', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS PALACIOS', 'codigo_postal' => 5351, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS ROBLES', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS SARMIENTOS', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'LOS TAMBILLOS', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'MACHIGASTA', 'codigo_postal' => 5311, 'provincia_id' => 12 ],
     [ 'nombre' => 'MALANZAN', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'MALLIGASTA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'MASCASIN', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'MEDANO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'MESILLAS BLANCAS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'MILAGRO', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'MIRANDA', 'codigo_postal' => 5367, 'provincia_id' => 12 ],
     [ 'nombre' => 'MOLLACO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'MONTE GRANDE', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'NACATE', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'NEPES', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'NONOGASTA', 'codigo_postal' => 5372, 'provincia_id' => 12 ],
     [ 'nombre' => 'NUEVA ESPERANZA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'OLPAS', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'OLTA', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'PACATALA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'PADERCITAS', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'PAGANCILLO', 'codigo_postal' => 5369, 'provincia_id' => 12 ],
     [ 'nombre' => 'PAGANZO', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'PALO LABRADO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'PARAJE MONTE GRANDE', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'PARECITAS', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'PASO SAN ISIDRO', 'codigo_postal' => 5351, 'provincia_id' => 12 ],
     [ 'nombre' => 'PASTOS LARGOS', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'PATQUIA', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'PE', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'PIEDRA DE TALAMPAYA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'PIEDRA LARGA', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'PIEDRA PINTADA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'PINCHAS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'PITUIL', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'PLAZA NUEVA', 'codigo_postal' => 5365, 'provincia_id' => 12 ],
     [ 'nombre' => 'PLAZA VIEJA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'POLCO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'PORTEZUELO DE LOS ARCE', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'POTRERO GRANDE', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO BLANCO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO DE AVILA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO DE LA ORILLA', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO DE LA PIEDRA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO DE LA YEGUA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO DE PIEDRA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO DEL MEDIO', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'POZO ESCONDIDO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUERTA DE LA QUEBRADA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUERTO ALEGRE', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUERTO ALEGRE', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUERTO DEL VALLE', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUESTO DE CARRIZO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUESTO DE LOS SANCHEZ', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUESTO DICHOSO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUESTO TALITA', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'PULUCHAN', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUNTA DE AGUA', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUNTA DE LOS LLANOS', 'codigo_postal' => 5384, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUNTA DEL CERRO', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'PUNTA DEL NEGRO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'QUEBRACHAL', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'QUEBRACHO HERRADO', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'QUEBRADA DE LOS CONDORES', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'QUEBRADA DEL VALLECITO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'REAL DEL CADILLO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'REPRESA DE LA PUNTA', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'REPRESA DEL MONTE', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'RETAMAL', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'RIO DE LAS CA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'RIOS DE LAS MESADAS', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'RIOS DE LOS COLCOLES', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'RIVADAVIA', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'SA', 'codigo_postal' => 5367, 'provincia_id' => 12 ],
     [ 'nombre' => 'SALANA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'SALICAS', 'codigo_postal' => 5327, 'provincia_id' => 12 ],
     [ 'nombre' => 'SALINAS DE BUSTOS', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'SALINAS DEL LEONCITO', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAMAY HUASI', 'codigo_postal' => 5360, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN AGUSTIN', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ANTONIO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ANTONIO', 'codigo_postal' => 5310, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ANTONIO', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ANTONIO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ANTONIO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN BERNARDO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN BERNARDO', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN CRISTOBAL', 'codigo_postal' => 5274, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN GUILLERMO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN IGNACIO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ISIDRO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN JAVIER', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN JOSE', 'codigo_postal' => 5475, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN JUAN', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN LORENZO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN MARTIN', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN MIGUEL', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN MIGUEL', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN NICOLAS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN NICOLAS', 'codigo_postal' => 5360, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN NICOLAS', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN PEDRO', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN PEDRO', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN RAFAEL', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN RAFAEL', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN RAMON', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN RAMON', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN ROQUE', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN SOLANO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'SAN VICENTE', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA ANA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA BARBARA', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA CLARA', 'codigo_postal' => 5351, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA CRUZ', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA CRUZ', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA CRUZ', 'codigo_postal' => 5470, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA CRUZ', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA ELENA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA FLORENTINA', 'codigo_postal' => 5360, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA LUCIA', 'codigo_postal' => 5380, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA RITA LA ZANJA', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA ROSA', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA TERESA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTA VERA CRUZ', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTO DOMINGO', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTO DOMINGO', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTO DOMINGO', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'SANTO DOMINGO FAMATINA', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'SCHAQUI', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'SE', 'codigo_postal' => 5310, 'provincia_id' => 12 ],
     [ 'nombre' => 'SIEMPRE VERDE', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'SIERRA BRAVA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'SIERRA DE LOS QUINTEROS', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'SIMBOLAR', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'SOLCA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'SURIYACO', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'TALA VERDE', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'TALAMUYUNA', 'codigo_postal' => 5304, 'provincia_id' => 12 ],
     [ 'nombre' => 'TALVA', 'codigo_postal' => 5381, 'provincia_id' => 12 ],
     [ 'nombre' => 'TAMA', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'TASQUIN', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'TERMAS', 'codigo_postal' => 5386, 'provincia_id' => 12 ],
     [ 'nombre' => 'TERMAS DE SANTA TERESITA', 'codigo_postal' => 5313, 'provincia_id' => 12 ],
     [ 'nombre' => 'TILIMUQUI', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'TINOCAN', 'codigo_postal' => 5313, 'provincia_id' => 12 ],
     [ 'nombre' => 'TORRECITAS', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'TOTORAL', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'TRAMPA DEL TIGRE', 'codigo_postal' => 5300, 'provincia_id' => 12 ],
     [ 'nombre' => 'TRES CERROS', 'codigo_postal' => 5361, 'provincia_id' => 12 ],
     [ 'nombre' => 'TRES CRUCES', 'codigo_postal' => 5383, 'provincia_id' => 12 ],
     [ 'nombre' => 'TUANI', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'TUIZON', 'codigo_postal' => 5385, 'provincia_id' => 12 ],
     [ 'nombre' => 'TUYUBIL', 'codigo_postal' => 5329, 'provincia_id' => 12 ],
     [ 'nombre' => 'UDPINANGO', 'codigo_postal' => 5311, 'provincia_id' => 12 ],
     [ 'nombre' => 'ULAPES', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'VALLE HERMOSO', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'VALLE HERMOSO', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'VERDE OLIVO', 'codigo_postal' => 5276, 'provincia_id' => 12 ],
     [ 'nombre' => 'VICHIGASTA', 'codigo_postal' => 5374, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA BUSTOS', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA CASANA', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA CASTELLI', 'codigo_postal' => 5355, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA CHEPES', 'codigo_postal' => 5471, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA MAZAN', 'codigo_postal' => 5313, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA NIDIA', 'codigo_postal' => 5473, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA SAN JOSE DE VINCHINA', 'codigo_postal' => 5359, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA SANAGASTA', 'codigo_postal' => 5301, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA SANTA RITA', 'codigo_postal' => 5275, 'provincia_id' => 12 ],
     [ 'nombre' => 'VILLA UNION', 'codigo_postal' => 5350, 'provincia_id' => 12 ],
     [ 'nombre' => 'VINCHINA', 'codigo_postal' => 5357, 'provincia_id' => 12 ]
	];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('localidades')->insert($this->localidades);
    }
}
