<?php

use Illuminate\Database\Seeder;

class ModelosAutosTableSeeder extends Seeder
{
    protected $modelos = [
      ['marca_id' => 1, 'nombre' => 'Legend'],
      ['marca_id' => 1, 'nombre' => 'Integra'],
      ['marca_id' => 1, 'nombre' => 'NSX'],
      ['marca_id' => 1, 'nombre' => 'Vigor'],
      ['marca_id' => 1, 'nombre' => 'TL'],
      ['marca_id' => 1, 'nombre' => 'RL'],
      ['marca_id' => 1, 'nombre' => 'SLX'],
      ['marca_id' => 1, 'nombre' => 'CL'],
      ['marca_id' => 1, 'nombre' => 'MDX'],
      ['marca_id' => 1, 'nombre' => 'RSX'],
      ['marca_id' => 1, 'nombre' => 'TSX'],
      ['marca_id' => 1, 'nombre' => 'RDX'],
      ['marca_id' => 1, 'nombre' => 'ZDX'],
      ['marca_id' => 2, 'nombre' => '164'],
      ['marca_id' => 2, 'nombre' => 'Spider'],
      ['marca_id' => 3, 'nombre' => 'Typ-1'],
      ['marca_id' => 3, 'nombre' => '2e'],
      ['marca_id' => 3, 'nombre' => 'Type-1h'],
      ['marca_id' => 4, 'nombre' => 'DB9'],
      ['marca_id' => 4, 'nombre' => 'Vanquish S'],
      ['marca_id' => 4, 'nombre' => 'DB9 Volante'],
      ['marca_id' => 4, 'nombre' => 'V8 Vantage'],
      ['marca_id' => 4, 'nombre' => 'Vantage'],
      ['marca_id' => 4, 'nombre' => 'DBS'],
      ['marca_id' => 4, 'nombre' => 'Rapide'],
      ['marca_id' => 4, 'nombre' => 'V8 Vantage S'],
      ['marca_id' => 4, 'nombre' => 'V12 Vantage'],
      ['marca_id' => 4, 'nombre' => 'Virage'],
      ['marca_id' => 5, 'nombre' => '5000S'],
      ['marca_id' => 5, 'nombre' => '4000s'],
      ['marca_id' => 5, 'nombre' => 'Quattro'],
      ['marca_id' => 5, 'nombre' => 'Coupe GT'],
      ['marca_id' => 5, 'nombre' => '5000CS Quattro'],
      ['marca_id' => 5, 'nombre' => '4000s Quattro'],
      ['marca_id' => 5, 'nombre' => '4000CS Quattro'],
      ['marca_id' => 5, 'nombre' => '4000'],
      ['marca_id' => 5, 'nombre' => '5000CS'],
      ['marca_id' => 5, 'nombre' => '90'],
      ['marca_id' => 5, 'nombre' => '80/90'],
      ['marca_id' => 5, 'nombre' => '80'],
      ['marca_id' => 5, 'nombre' => '100'],
      ['marca_id' => 5, 'nombre' => '200'],
      ['marca_id' => 5, 'nombre' => 'V8'],
      ['marca_id' => 5, 'nombre' => 'Coupe Quattro'],
      ['marca_id' => 5, 'nombre' => 'S4'],
      ['marca_id' => 5, 'nombre' => 'Cabriolet'],
      ['marca_id' => 5, 'nombre' => 'riolet'],
      ['marca_id' => 5, 'nombre' => 'S6'],
      ['marca_id' => 5, 'nombre' => 'A6'],
      ['marca_id' => 5, 'nombre' => 'A4'],
      ['marca_id' => 5, 'nombre' => 'A8'],
      ['marca_id' => 5, 'nombre' => 'TT'],
      ['marca_id' => 5, 'nombre' => 'S8'],
      ['marca_id' => 5, 'nombre' => 'Allroad'],
      ['marca_id' => 5, 'nombre' => 'RS6'],
      ['marca_id' => 5, 'nombre' => 'RS 6'],
      ['marca_id' => 5, 'nombre' => 'A3'],
      ['marca_id' => 5, 'nombre' => 'Q7'],
      ['marca_id' => 5, 'nombre' => 'RS4'],
      ['marca_id' => 5, 'nombre' => 'RS 4'],
      ['marca_id' => 5, 'nombre' => 'S5'],
      ['marca_id' => 5, 'nombre' => 'R8'],
      ['marca_id' => 5, 'nombre' => 'A5'],
      ['marca_id' => 5, 'nombre' => 'Q5'],
      ['marca_id' => 5, 'nombre' => 'A7'],
      ['marca_id' => 6, 'nombre' => 'Mini'],
      ['marca_id' => 6, 'nombre' => 'Mini Cooper'],
      ['marca_id' => 6, 'nombre' => 'Mini Cooper S'],
      ['marca_id' => 7, 'nombre' => 'Arnage'],
      ['marca_id' => 7, 'nombre' => 'Continental'],
      ['marca_id' => 7, 'nombre' => 'Azure'],
      ['marca_id' => 7, 'nombre' => 'Continental GT'],
      ['marca_id' => 7, 'nombre' => 'Continental Flying Spur'],
      ['marca_id' => 7, 'nombre' => 'Continental GTC'],
      ['marca_id' => 7, 'nombre' => 'Brooklands'],
      ['marca_id' => 7, 'nombre' => 'Continental Super'],
      ['marca_id' => 7, 'nombre' => 'Azure T'],
      ['marca_id' => 7, 'nombre' => 'Mulsanne'],
      ['marca_id' => 8, 'nombre' => '600'],
      ['marca_id' => 8, 'nombre' => '6 Series'],
      ['marca_id' => 8, 'nombre' => '3 Series'],
      ['marca_id' => 8, 'nombre' => '5 Series'],
      ['marca_id' => 8, 'nombre' => '7 Series'],
      ['marca_id' => 8, 'nombre' => '8 Series'],
      ['marca_id' => 8, 'nombre' => 'M5'],
      ['marca_id' => 8, 'nombre' => 'M3'],
      ['marca_id' => 8, 'nombre' => 'Z3'],
      ['marca_id' => 8, 'nombre' => 'X5'],
      ['marca_id' => 8, 'nombre' => 'M'],
      ['marca_id' => 8, 'nombre' => 'Z8'],
      ['marca_id' => 8, 'nombre' => '525'],
      ['marca_id' => 8, 'nombre' => '530'],
      ['marca_id' => 8, 'nombre' => '745'],
      ['marca_id' => 8, 'nombre' => '760'],
      ['marca_id' => 8, 'nombre' => 'Z4'],
      ['marca_id' => 8, 'nombre' => '325'],
      ['marca_id' => 8, 'nombre' => '545'],
      ['marca_id' => 8, 'nombre' => '645'],
      ['marca_id' => 8, 'nombre' => 'X3'],
      ['marca_id' => 8, 'nombre' => '330'],
      ['marca_id' => 8, 'nombre' => '550'],
      ['marca_id' => 8, 'nombre' => '650'],
      ['marca_id' => 8, 'nombre' => '750'],
      ['marca_id' => 8, 'nombre' => 'M6'],
      ['marca_id' => 8, 'nombre' => 'M Roadster'],
      ['marca_id' => 8, 'nombre' => 'Z4 M'],
      ['marca_id' => 8, 'nombre' => 'Alpina B7'],
      ['marca_id' => 8, 'nombre' => '1 Series'],
      ['marca_id' => 8, 'nombre' => 'X6'],
      ['marca_id' => 8, 'nombre' => 'Z4 M Roadster'],
      ['marca_id' => 8, 'nombre' => 'X5 M'],
      ['marca_id' => 8, 'nombre' => 'X6 M'],
      ['marca_id' => 9, 'nombre' => 'Veyron'],
      ['marca_id' => 10, 'nombre' => 'Special'],
      ['marca_id' => 10, 'nombre' => 'Riviera'],
      ['marca_id' => 10, 'nombre' => 'Electra'],
      ['marca_id' => 10, 'nombre' => 'Century'],
      ['marca_id' => 10, 'nombre' => 'Skyhawk'],
      ['marca_id' => 10, 'nombre' => 'Somerset'],
      ['marca_id' => 10, 'nombre' => 'LeSabre'],
      ['marca_id' => 10, 'nombre' => 'Regal'],
      ['marca_id' => 10, 'nombre' => 'Skylark'],
      ['marca_id' => 10, 'nombre' => 'Reatta'],
      ['marca_id' => 10, 'nombre' => 'Estate'],
      ['marca_id' => 10, 'nombre' => 'Coachbuilder'],
      ['marca_id' => 10, 'nombre' => 'Park Avenue'],
      ['marca_id' => 10, 'nombre' => 'Roadmaster'],
      ['marca_id' => 10, 'nombre' => 'Hearse'],
      ['marca_id' => 10, 'nombre' => 'Rendezvous'],
      ['marca_id' => 10, 'nombre' => 'Rainier'],
      ['marca_id' => 10, 'nombre' => 'LaCrosse'],
      ['marca_id' => 10, 'nombre' => 'Terraza'],
      ['marca_id' => 10, 'nombre' => 'Lucerne'],
      ['marca_id' => 10, 'nombre' => 'Enclave'],
      ['marca_id' => 10, 'nombre' => 'Verano'],
      ['marca_id' => 11, 'nombre' => 'Fleetwood'],
      ['marca_id' => 11, 'nombre' => 'Seville'],
      ['marca_id' => 11, 'nombre' => 'Allante'],
      ['marca_id' => 11, 'nombre' => 'Brougham'],
      ['marca_id' => 11, 'nombre' => 'DeVille'],
      ['marca_id' => 11, 'nombre' => 'Eldorado'],
      ['marca_id' => 11, 'nombre' => 'Sixty Special'],
      ['marca_id' => 11, 'nombre' => 'Catera'],
      ['marca_id' => 11, 'nombre' => 'Escalade'],
      ['marca_id' => 11, 'nombre' => 'Escalade EXT'],
      ['marca_id' => 11, 'nombre' => 'CTS'],
      ['marca_id' => 11, 'nombre' => 'Escalade ESV'],
      ['marca_id' => 11, 'nombre' => 'SRX'],
      ['marca_id' => 11, 'nombre' => 'XLR'],
      ['marca_id' => 11, 'nombre' => 'STS'],
      ['marca_id' => 11, 'nombre' => 'DTS'],
      ['marca_id' => 11, 'nombre' => 'XLR-V'],
      ['marca_id' => 11, 'nombre' => 'CTS-V'],
      ['marca_id' => 11, 'nombre' => 'STS-V'],
      ['marca_id' => 13, 'nombre' => 'Corvette'],
      ['marca_id' => 13, 'nombre' => 'Corvair'],
      ['marca_id' => 13, 'nombre' => 'Corvair 500'],
      ['marca_id' => 13, 'nombre' => 'Camaro'],
      ['marca_id' => 13, 'nombre' => 'Bel Air'],
      ['marca_id' => 13, 'nombre' => 'Vega'],
      ['marca_id' => 13, 'nombre' => 'Monte Carlo'],
      ['marca_id' => 13, 'nombre' => 'Monza'],
      ['marca_id' => 13, 'nombre' => 'Caprice'],
      ['marca_id' => 13, 'nombre' => 'LUV'],
      ['marca_id' => 13, 'nombre' => 'Citation'],
      ['marca_id' => 13, 'nombre' => '1500'],
      ['marca_id' => 13, 'nombre' => '2500'],
      ['marca_id' => 13, 'nombre' => '3500'],
      ['marca_id' => 13, 'nombre' => 'APV'],
      ['marca_id' => 13, 'nombre' => 'Astro'],
      ['marca_id' => 13, 'nombre' => 'Beretta'],
      ['marca_id' => 13, 'nombre' => 'Blazer'],
      ['marca_id' => 13, 'nombre' => 'Cavalier'],
      ['marca_id' => 13, 'nombre' => 'Corsica'],
      ['marca_id' => 13, 'nombre' => 'G-Series G10'],
      ['marca_id' => 13, 'nombre' => 'G-Series G20'],
      ['marca_id' => 13, 'nombre' => 'G-Series G30'],
      ['marca_id' => 13, 'nombre' => 'Lumina'],
      ['marca_id' => 13, 'nombre' => 'Lumina APV'],
      ['marca_id' => 13, 'nombre' => 'S10 Blazer'],
      ['marca_id' => 13, 'nombre' => 'S10'],
      ['marca_id' => 13, 'nombre' => 'Sportvan G10'],
      ['marca_id' => 13, 'nombre' => 'Sportvan G20'],
      ['marca_id' => 13, 'nombre' => 'Sportvan G30'],
      ['marca_id' => 13, 'nombre' => 'Suburban 1500'],
      ['marca_id' => 13, 'nombre' => 'Suburban 2500'],
      ['marca_id' => 13, 'nombre' => 'Caprice Classic'],
      ['marca_id' => 13, 'nombre' => 'Impala SS'],
      ['marca_id' => 13, 'nombre' => 'Impala'],
      ['marca_id' => 13, 'nombre' => 'K5 Blazer'],
      ['marca_id' => 13, 'nombre' => 'Tahoe'],
      ['marca_id' => 13, 'nombre' => 'Express 1500'],
      ['marca_id' => 13, 'nombre' => 'Express 2500'],
      ['marca_id' => 13, 'nombre' => 'Express 3500'],
      ['marca_id' => 13, 'nombre' => 'G-Series 1500'],
      ['marca_id' => 13, 'nombre' => 'G-Series 2500'],
      ['marca_id' => 13, 'nombre' => 'Malibu'],
      ['marca_id' => 13, 'nombre' => 'G-Series 3500'],
      ['marca_id' => 13, 'nombre' => 'Venture'],
      ['marca_id' => 13, 'nombre' => 'Metro'],
      ['marca_id' => 13, 'nombre' => 'Prizm'],
      ['marca_id' => 13, 'nombre' => 'Tracker'],
      ['marca_id' => 13, 'nombre' => 'Silverado'],
      ['marca_id' => 13, 'nombre' => 'Silverado 1500'],
      ['marca_id' => 13, 'nombre' => 'Silverado 2500'],
      ['marca_id' => 13, 'nombre' => 'Silverado 3500'],
      ['marca_id' => 13, 'nombre' => 'Avalanche'],
      ['marca_id' => 13, 'nombre' => 'Trailblazer'],
      ['marca_id' => 13, 'nombre' => 'Avalanche 1500'],
      ['marca_id' => 13, 'nombre' => 'Avalanche 2500'],
      ['marca_id' => 13, 'nombre' => 'SSR'],
      ['marca_id' => 13, 'nombre' => 'Aveo'],
      ['marca_id' => 13, 'nombre' => 'Classic'],
      ['marca_id' => 13, 'nombre' => 'Colorado'],
      ['marca_id' => 13, 'nombre' => 'Cobalt'],
      ['marca_id' => 13, 'nombre' => 'Equinox'],
      ['marca_id' => 13, 'nombre' => 'Uplander'],
      ['marca_id' => 13, 'nombre' => 'Suburban'],
      ['marca_id' => 13, 'nombre' => 'Silverado 3500HD'],
      ['marca_id' => 13, 'nombre' => 'HHR Panel'],
      ['marca_id' => 13, 'nombre' => 'Malibu Maxx'],
      ['marca_id' => 13, 'nombre' => 'HHR'],
      ['marca_id' => 13, 'nombre' => 'Silverado Hybrid'],
      ['marca_id' => 13, 'nombre' => 'Express'],
      ['marca_id' => 13, 'nombre' => 'Cobalt SS'],
      ['marca_id' => 13, 'nombre' => 'Traverse'],
      ['marca_id' => 13, 'nombre' => 'Volt'],
      ['marca_id' => 13, 'nombre' => 'Cruze'],
      ['marca_id' => 13, 'nombre' => 'Sonic'],
      ['marca_id' => 14, 'nombre' => 'Imperial'],
      ['marca_id' => 14, 'nombre' => 'Fifth Ave'],
      ['marca_id' => 14, 'nombre' => 'LeBaron'],
      ['marca_id' => 14, 'nombre' => 'New Yorker'],
      ['marca_id' => 14, 'nombre' => 'Town & Country'],
      ['marca_id' => 14, 'nombre' => 'Concorde'],
      ['marca_id' => 14, 'nombre' => 'LHS'],
      ['marca_id' => 14, 'nombre' => 'Cirrus'],
      ['marca_id' => 14, 'nombre' => 'Sebring'],
      ['marca_id' => 14, 'nombre' => '300M'],
      ['marca_id' => 14, 'nombre' => '300'],
      ['marca_id' => 14, 'nombre' => 'Grand Voyager'],
      ['marca_id' => 14, 'nombre' => 'Voyager'],
      ['marca_id' => 14, 'nombre' => 'PT Cruiser'],
      ['marca_id' => 14, 'nombre' => 'Prowler'],
      ['marca_id' => 14, 'nombre' => 'Crossfire'],
      ['marca_id' => 14, 'nombre' => 'Pacifica'],
      ['marca_id' => 14, 'nombre' => '300C'],
      ['marca_id' => 14, 'nombre' => 'Crossfire Roadster'],
      ['marca_id' => 14, 'nombre' => 'Aspen'],
      ['marca_id' => 14, 'nombre' => '200'],
      ['marca_id' => 15, 'nombre' => '2CV'],
      ['marca_id' => 15, 'nombre' => 'SM'],
      ['marca_id' => 15, 'nombre' => 'CX'],
      ['marca_id' => 16, 'nombre' => 'Sparrow'],
      ['marca_id' => 17, 'nombre' => 'Lanos'],
      ['marca_id' => 17, 'nombre' => 'Leganza'],
      ['marca_id' => 17, 'nombre' => 'Nubira'],
      ['marca_id' => 18, 'nombre' => 'Charade'],
      ['marca_id' => 18, 'nombre' => 'Rocky'],
      ['marca_id' => 19, 'nombre' => 'Charger'],
      ['marca_id' => 19, 'nombre' => 'Aspen'],
      ['marca_id' => 19, 'nombre' => 'Omni'],
      ['marca_id' => 19, 'nombre' => 'Aries'],
      ['marca_id' => 19, 'nombre' => 'Daytona'],
      ['marca_id' => 19, 'nombre' => 'Caravan'],
      ['marca_id' => 19, 'nombre' => 'Colt'],
      ['marca_id' => 19, 'nombre' => 'Viper'],
      ['marca_id' => 19, 'nombre' => 'D150 Club'],
      ['marca_id' => 19, 'nombre' => 'D150'],
      ['marca_id' => 19, 'nombre' => 'D250 Club'],
      ['marca_id' => 19, 'nombre' => 'D250'],
      ['marca_id' => 19, 'nombre' => 'D350 Club'],
      ['marca_id' => 19, 'nombre' => 'D350'],
      ['marca_id' => 19, 'nombre' => 'Dakota Club'],
      ['marca_id' => 19, 'nombre' => 'Dakota'],
      ['marca_id' => 19, 'nombre' => 'Dynasty'],
      ['marca_id' => 19, 'nombre' => 'Grand Caravan'],
      ['marca_id' => 19, 'nombre' => 'Monaco'],
      ['marca_id' => 19, 'nombre' => 'Ram 50'],
      ['marca_id' => 19, 'nombre' => 'Ram Van B150'],
      ['marca_id' => 19, 'nombre' => 'Ram Van B250'],
      ['marca_id' => 19, 'nombre' => 'Ram Van B350'],
      ['marca_id' => 19, 'nombre' => 'Ram Wagon B150'],
      ['marca_id' => 19, 'nombre' => 'Ram Wagon B250'],
      ['marca_id' => 19, 'nombre' => 'Ram Wagon B350'],
      ['marca_id' => 19, 'nombre' => 'Ramcharger'],
      ['marca_id' => 19, 'nombre' => 'Shadow'],
      ['marca_id' => 19, 'nombre' => 'Spirit'],
      ['marca_id' => 19, 'nombre' => 'Stealth'],
      ['marca_id' => 19, 'nombre' => 'Viper RT/10'],
      ['marca_id' => 19, 'nombre' => 'Intrepid'],
      ['marca_id' => 19, 'nombre' => 'Ram'],
      ['marca_id' => 19, 'nombre' => 'Ram 1500'],
      ['marca_id' => 19, 'nombre' => 'Ram 2500'],
      ['marca_id' => 19, 'nombre' => 'Ram 3500'],
      ['marca_id' => 19, 'nombre' => 'Avenger'],
      ['marca_id' => 19, 'nombre' => 'Neon'],
      ['marca_id' => 19, 'nombre' => 'Ram 1500 Club'],
      ['marca_id' => 19, 'nombre' => 'Ram 2500 Club'],
      ['marca_id' => 19, 'nombre' => 'Ram 3500 Club'],
      ['marca_id' => 19, 'nombre' => 'Ram Van 1500'],
      ['marca_id' => 19, 'nombre' => 'Ram Van 2500'],
      ['marca_id' => 19, 'nombre' => 'Ram Van 3500'],
      ['marca_id' => 19, 'nombre' => 'Stratus'],
      ['marca_id' => 19, 'nombre' => 'Durango'],
      ['marca_id' => 19, 'nombre' => 'Magnum'],
      ['marca_id' => 19, 'nombre' => 'Sprinter'],
      ['marca_id' => 19, 'nombre' => 'Nitro'],
      ['marca_id' => 19, 'nombre' => 'Caliber'],
      ['marca_id' => 19, 'nombre' => 'Challenger'],
      ['marca_id' => 19, 'nombre' => 'Journey'],
      ['marca_id' => 20, 'nombre' => 'Talon'],
      ['marca_id' => 20, 'nombre' => 'Premier'],
      ['marca_id' => 20, 'nombre' => 'Summit'],
      ['marca_id' => 20, 'nombre' => 'Vision'],
      ['marca_id' => 21, 'nombre' => 'Rockette'],
      ['marca_id' => 22, 'nombre' => 'F430'],
      ['marca_id' => 22, 'nombre' => '612 Scaglietti'],
      ['marca_id' => 22, 'nombre' => 'F430 Spider'],
      ['marca_id' => 22, 'nombre' => '599 GTB Fiorano'],
      ['marca_id' => 22, 'nombre' => '430 Scuderia'],
      ['marca_id' => 22, 'nombre' => 'California'],
      ['marca_id' => 22, 'nombre' => '458 Italia'],
      ['marca_id' => 22, 'nombre' => 'FF'],
      ['marca_id' => 23, 'nombre' => '500'],
      ['marca_id' => 23, 'nombre' => 'Nuova 500'],
      ['marca_id' => 24, 'nombre' => 'Fillmore'],
      ['marca_id' => 25, 'nombre' => 'Hemisfear'],
      ['marca_id' => 26, 'nombre' => 'Model T'],
      ['marca_id' => 26, 'nombre' => 'Thunderbird'],
      ['marca_id' => 26, 'nombre' => 'E-Series'],
      ['marca_id' => 26, 'nombre' => 'Mustang'],
      ['marca_id' => 26, 'nombre' => 'Galaxie'],
      ['marca_id' => 26, 'nombre' => 'Fairlane'],
      ['marca_id' => 26, 'nombre' => 'Falcon'],
      ['marca_id' => 26, 'nombre' => 'Country'],
      ['marca_id' => 26, 'nombre' => 'Torino'],
      ['marca_id' => 26, 'nombre' => 'Bronco II'],
      ['marca_id' => 26, 'nombre' => 'Laser'],
      ['marca_id' => 26, 'nombre' => 'EXP'],
      ['marca_id' => 26, 'nombre' => 'Ranger'],
      ['marca_id' => 26, 'nombre' => 'Escort'],
      ['marca_id' => 26, 'nombre' => 'Tempo'],
      ['marca_id' => 26, 'nombre' => 'LTD'],
      ['marca_id' => 26, 'nombre' => 'F250'],
      ['marca_id' => 26, 'nombre' => 'F150'],
      ['marca_id' => 26, 'nombre' => 'E250'],
      ['marca_id' => 26, 'nombre' => 'LTD Crown Victoria'],
      ['marca_id' => 26, 'nombre' => 'Bronco'],
      ['marca_id' => 26, 'nombre' => 'E150'],
      ['marca_id' => 26, 'nombre' => 'F-Series'],
      ['marca_id' => 26, 'nombre' => 'Taurus'],
      ['marca_id' => 26, 'nombre' => 'Aerostar'],
      ['marca_id' => 26, 'nombre' => 'Courier'],
      ['marca_id' => 26, 'nombre' => 'Festiva'],
      ['marca_id' => 26, 'nombre' => 'Probe'],
      ['marca_id' => 26, 'nombre' => 'Explorer'],
      ['marca_id' => 26, 'nombre' => 'Crown Victoria'],
      ['marca_id' => 26, 'nombre' => 'Club Wagon'],
      ['marca_id' => 26, 'nombre' => 'Econoline E150'],
      ['marca_id' => 26, 'nombre' => 'Econoline E250'],
      ['marca_id' => 26, 'nombre' => 'Econoline E350'],
      ['marca_id' => 26, 'nombre' => 'F350'],
      ['marca_id' => 26, 'nombre' => 'Lightning'],
      ['marca_id' => 26, 'nombre' => 'Aspire'],
      ['marca_id' => 26, 'nombre' => 'Windstar'],
      ['marca_id' => 26, 'nombre' => 'Contour'],
      ['marca_id' => 26, 'nombre' => 'Expedition'],
      ['marca_id' => 26, 'nombre' => 'Th!nk'],
      ['marca_id' => 26, 'nombre' => 'Explorer Sport Trac'],
      ['marca_id' => 26, 'nombre' => 'Escape'],
      ['marca_id' => 26, 'nombre' => 'Excursion'],
      ['marca_id' => 26, 'nombre' => 'Explorer Sport'],
      ['marca_id' => 26, 'nombre' => 'Focus'],
      ['marca_id' => 26, 'nombre' => 'Fiesta'],
      ['marca_id' => 26, 'nombre' => 'ZX2'],
      ['marca_id' => 26, 'nombre' => 'Escort ZX2'],
      ['marca_id' => 26, 'nombre' => 'Freestar'],
      ['marca_id' => 26, 'nombre' => 'E350'],
      ['marca_id' => 26, 'nombre' => 'GT'],
      ['marca_id' => 26, 'nombre' => 'Freestyle'],
      ['marca_id' => 26, 'nombre' => 'Five Hundred'],
      ['marca_id' => 26, 'nombre' => 'F-250 Super Duty'],
      ['marca_id' => 26, 'nombre' => 'F-350 Super Duty'],
      ['marca_id' => 26, 'nombre' => 'E-350 Super Duty'],
      ['marca_id' => 26, 'nombre' => 'E-350 Super Duty Van'],
      ['marca_id' => 26, 'nombre' => 'Fusion'],
      ['marca_id' => 26, 'nombre' => 'F-Series Super Duty'],
      ['marca_id' => 26, 'nombre' => 'GT500'],
      ['marca_id' => 26, 'nombre' => 'Edge'],
      ['marca_id' => 26, 'nombre' => 'Expedition EL'],
      ['marca_id' => 26, 'nombre' => 'Taurus X'],
      ['marca_id' => 26, 'nombre' => 'F450'],
      ['marca_id' => 26, 'nombre' => 'Flex'],
      ['marca_id' => 26, 'nombre' => 'Transit Connect'],
      ['marca_id' => 26, 'nombre' => 'C-MAX Hybrid'],
      ['marca_id' => 26, 'nombre' => 'Focus ST'],
      ['marca_id' => 27, 'nombre' => 'Metro'],
      ['marca_id' => 27, 'nombre' => 'Prizm'],
      ['marca_id' => 27, 'nombre' => 'Storm'],
      ['marca_id' => 27, 'nombre' => 'Tracker'],
      ['marca_id' => 28, 'nombre' => '1500'],
      ['marca_id' => 28, 'nombre' => '2500'],
      ['marca_id' => 28, 'nombre' => '3500'],
      ['marca_id' => 28, 'nombre' => '1500 Club Coupe'],
      ['marca_id' => 28, 'nombre' => '2500 Club Coupe'],
      ['marca_id' => 28, 'nombre' => '3500 Club Coupe'],
      ['marca_id' => 28, 'nombre' => 'Jimmy'],
      ['marca_id' => 28, 'nombre' => 'Rally Wagon 1500'],
      ['marca_id' => 28, 'nombre' => 'Rally Wagon 2500'],
      ['marca_id' => 28, 'nombre' => 'Rally Wagon 3500'],
      ['marca_id' => 28, 'nombre' => 'Safari'],
      ['marca_id' => 28, 'nombre' => 'Sonoma Club'],
      ['marca_id' => 28, 'nombre' => 'Sonoma'],
      ['marca_id' => 28, 'nombre' => 'Suburban 1500'],
      ['marca_id' => 28, 'nombre' => 'Suburban 2500'],
      ['marca_id' => 28, 'nombre' => 'Vandura 1500'],
      ['marca_id' => 28, 'nombre' => 'Vandura 2500'],
      ['marca_id' => 28, 'nombre' => 'Vandura 3500'],
      ['marca_id' => 28, 'nombre' => 'Yukon'],
      ['marca_id' => 28, 'nombre' => 'Sonoma Club Coupe'],
      ['marca_id' => 28, 'nombre' => 'Rally Wagon G2500'],
      ['marca_id' => 28, 'nombre' => 'Rally Wagon G3500'],
      ['marca_id' => 28, 'nombre' => 'Vandura G1500'],
      ['marca_id' => 28, 'nombre' => 'Vandura G2500'],
      ['marca_id' => 28, 'nombre' => 'Vandura G3500'],
      ['marca_id' => 28, 'nombre' => 'Savana 1500'],
      ['marca_id' => 28, 'nombre' => 'Savana 2500'],
      ['marca_id' => 28, 'nombre' => 'Savana 3500'],
      ['marca_id' => 28, 'nombre' => 'Envoy'],
      ['marca_id' => 28, 'nombre' => 'EV1'],
      ['marca_id' => 28, 'nombre' => 'Sierra 1500'],
      ['marca_id' => 28, 'nombre' => 'Sierra 2500'],
      ['marca_id' => 28, 'nombre' => 'Sierra 3500'],
      ['marca_id' => 28, 'nombre' => 'Yukon Denali'],
      ['marca_id' => 28, 'nombre' => 'Yukon XL 1500'],
      ['marca_id' => 28, 'nombre' => 'Yukon XL 2500'],
      ['marca_id' => 28, 'nombre' => 'Envoy XL'],
      ['marca_id' => 28, 'nombre' => 'Canyon'],
      ['marca_id' => 28, 'nombre' => 'Envoy XUV'],
      ['marca_id' => 28, 'nombre' => 'Sierra Denali'],
      ['marca_id' => 28, 'nombre' => 'Sierra 3500HD'],
      ['marca_id' => 28, 'nombre' => 'Sierra 2500HD'],
      ['marca_id' => 28, 'nombre' => 'Yukon XL'],
      ['marca_id' => 28, 'nombre' => 'Savana Cargo Van'],
      ['marca_id' => 28, 'nombre' => 'Sierra Hybrid'],
      ['marca_id' => 28, 'nombre' => 'Savana'],
      ['marca_id' => 28, 'nombre' => 'Acadia'],
      ['marca_id' => 28, 'nombre' => 'Sierra'],
      ['marca_id' => 28, 'nombre' => 'Terrain'],
      ['marca_id' => 29, 'nombre' => 'Minx Magnificent'],
      ['marca_id' => 30, 'nombre' => 'VS Commodore'],
      ['marca_id' => 30, 'nombre' => 'Monaro'],
      ['marca_id' => 31, 'nombre' => 'Civic'],
      ['marca_id' => 31, 'nombre' => 'Accord'],
      ['marca_id' => 31, 'nombre' => 'CR-X'],
      ['marca_id' => 31, 'nombre' => 'Prelude'],
      ['marca_id' => 31, 'nombre' => 'del Sol'],
      ['marca_id' => 31, 'nombre' => 'Passport'],
      ['marca_id' => 31, 'nombre' => 'Odyssey'],
      ['marca_id' => 31, 'nombre' => 'CR-V'],
      ['marca_id' => 31, 'nombre' => 'Insight'],
      ['marca_id' => 31, 'nombre' => 'S2000'],
      ['marca_id' => 31, 'nombre' => 'Pilot'],
      ['marca_id' => 31, 'nombre' => 'Element'],
      ['marca_id' => 31, 'nombre' => 'Civic Si'],
      ['marca_id' => 31, 'nombre' => 'Civic GX'],
      ['marca_id' => 31, 'nombre' => 'Ridgeline'],
      ['marca_id' => 31, 'nombre' => 'Fit'],
      ['marca_id' => 31, 'nombre' => 'Accord Crosstour'],
      ['marca_id' => 31, 'nombre' => 'CR-Z'],
      ['marca_id' => 31, 'nombre' => 'FCX Clarity'],
      ['marca_id' => 31, 'nombre' => 'Crosstour'],
      ['marca_id' => 32, 'nombre' => 'H1'],
      ['marca_id' => 32, 'nombre' => 'H2'],
      ['marca_id' => 32, 'nombre' => 'H2 SUT'],
      ['marca_id' => 32, 'nombre' => 'H2 SUV'],
      ['marca_id' => 32, 'nombre' => 'H3'],
      ['marca_id' => 32, 'nombre' => 'H3T'],
      ['marca_id' => 33, 'nombre' => 'Elantra'],
      ['marca_id' => 33, 'nombre' => 'Excel'],
      ['marca_id' => 33, 'nombre' => 'Scoupe'],
      ['marca_id' => 33, 'nombre' => 'Sonata'],
      ['marca_id' => 33, 'nombre' => 'Accent'],
      ['marca_id' => 33, 'nombre' => 'Tiburon'],
      ['marca_id' => 33, 'nombre' => 'Santa Fe'],
      ['marca_id' => 33, 'nombre' => 'XG300'],
      ['marca_id' => 33, 'nombre' => 'XG350'],
      ['marca_id' => 33, 'nombre' => 'Tucson'],
      ['marca_id' => 33, 'nombre' => 'Azera'],
      ['marca_id' => 33, 'nombre' => 'Veracruz'],
      ['marca_id' => 33, 'nombre' => 'Entourage'],
      ['marca_id' => 33, 'nombre' => 'Genesis'],
      ['marca_id' => 33, 'nombre' => 'Genesis Coupe'],
      ['marca_id' => 33, 'nombre' => 'Equus'],
      ['marca_id' => 33, 'nombre' => 'HED-5'],
      ['marca_id' => 33, 'nombre' => 'Veloster'],
      ['marca_id' => 34, 'nombre' => 'G'],
      ['marca_id' => 34, 'nombre' => 'M'],
      ['marca_id' => 34, 'nombre' => 'Q'],
      ['marca_id' => 34, 'nombre' => 'J'],
      ['marca_id' => 34, 'nombre' => 'I'],
      ['marca_id' => 34, 'nombre' => 'QX'],
      ['marca_id' => 34, 'nombre' => 'G35'],
      ['marca_id' => 34, 'nombre' => 'FX'],
      ['marca_id' => 34, 'nombre' => 'QX56'],
      ['marca_id' => 34, 'nombre' => 'G37'],
      ['marca_id' => 34, 'nombre' => 'EX'],
      ['marca_id' => 34, 'nombre' => 'G25'],
      ['marca_id' => 34, 'nombre' => 'IPL G'],
      ['marca_id' => 34, 'nombre' => 'JX'],
      ['marca_id' => 35, 'nombre' => 'Amigo'],
      ['marca_id' => 35, 'nombre' => 'Impulse'],
      ['marca_id' => 35, 'nombre' => 'Rodeo'],
      ['marca_id' => 35, 'nombre' => 'Space'],
      ['marca_id' => 35, 'nombre' => 'Stylus'],
      ['marca_id' => 35, 'nombre' => 'Trooper'],
      ['marca_id' => 35, 'nombre' => 'Hombre'],
      ['marca_id' => 35, 'nombre' => 'Oasis'],
      ['marca_id' => 35, 'nombre' => 'Hombre Space'],
      ['marca_id' => 35, 'nombre' => 'VehiCROSS'],
      ['marca_id' => 35, 'nombre' => 'Rodeo Sport'],
      ['marca_id' => 35, 'nombre' => 'Axiom'],
      ['marca_id' => 35, 'nombre' => 'Ascender'],
      ['marca_id' => 35, 'nombre' => 'i-Series'],
      ['marca_id' => 35, 'nombre' => 'i-280'],
      ['marca_id' => 35, 'nombre' => 'i-350'],
      ['marca_id' => 35, 'nombre' => 'i-290'],
      ['marca_id' => 35, 'nombre' => 'i-370'],
      ['marca_id' => 36, 'nombre' => 'XJ Series'],
      ['marca_id' => 36, 'nombre' => 'XK Series'],
      ['marca_id' => 36, 'nombre' => 'S-Type'],
      ['marca_id' => 36, 'nombre' => 'X-Type'],
      ['marca_id' => 36, 'nombre' => 'XK'],
      ['marca_id' => 36, 'nombre' => 'XJ'],
      ['marca_id' => 36, 'nombre' => 'XF'],
      ['marca_id' => 37, 'nombre' => 'Cherokee'],
      ['marca_id' => 37, 'nombre' => 'Comanche'],
      ['marca_id' => 37, 'nombre' => 'Wrangler'],
      ['marca_id' => 37, 'nombre' => 'Grand Cherokee'],
      ['marca_id' => 37, 'nombre' => 'Liberty'],
      ['marca_id' => 37, 'nombre' => 'Commander'],
      ['marca_id' => 37, 'nombre' => 'Compass'],
      ['marca_id' => 37, 'nombre' => 'Patriot'],
      ['marca_id' => 38, 'nombre' => 'Interceptor'],
      ['marca_id' => 39, 'nombre' => 'Sephia'],
      ['marca_id' => 39, 'nombre' => 'Sportage'],
      ['marca_id' => 39, 'nombre' => 'Mentor'],
      ['marca_id' => 39, 'nombre' => 'Spectra'],
      ['marca_id' => 39, 'nombre' => 'Rio'],
      ['marca_id' => 39, 'nombre' => 'Optima'],
      ['marca_id' => 39, 'nombre' => 'Sedona'],
      ['marca_id' => 39, 'nombre' => 'Sorento'],
      ['marca_id' => 39, 'nombre' => 'Amanti'],
      ['marca_id' => 39, 'nombre' => 'Spectra5'],
      ['marca_id' => 39, 'nombre' => 'Carens'],
      ['marca_id' => 39, 'nombre' => 'Rondo'],
      ['marca_id' => 39, 'nombre' => 'Rio5'],
      ['marca_id' => 39, 'nombre' => 'Mohave/Borrego'],
      ['marca_id' => 39, 'nombre' => 'Borrego'],
      ['marca_id' => 39, 'nombre' => 'Soul'],
      ['marca_id' => 39, 'nombre' => 'Forte'],
      ['marca_id' => 40, 'nombre' => 'Countach'],
      ['marca_id' => 40, 'nombre' => 'Diablo'],
      ['marca_id' => 40, 'nombre' => 'Murciélago'],
      ['marca_id' => 40, 'nombre' => 'Gallardo'],
      ['marca_id' => 40, 'nombre' => 'Reventón'],
      ['marca_id' => 40, 'nombre' => 'Murciélago LP640'],
      ['marca_id' => 40, 'nombre' => 'Aventador'],
      ['marca_id' => 41, 'nombre' => 'Range Rover'],
      ['marca_id' => 41, 'nombre' => 'Sterling'],
      ['marca_id' => 41, 'nombre' => 'Defender'],
      ['marca_id' => 41, 'nombre' => 'Range Rover Classic'],
      ['marca_id' => 41, 'nombre' => 'Defender 110'],
      ['marca_id' => 41, 'nombre' => 'Discovery'],
      ['marca_id' => 41, 'nombre' => 'Defender 90'],
      ['marca_id' => 41, 'nombre' => 'Discovery Series II'],
      ['marca_id' => 41, 'nombre' => 'Freelander'],
      ['marca_id' => 41, 'nombre' => 'LR3'],
      ['marca_id' => 41, 'nombre' => 'Range Rover Sport'],
      ['marca_id' => 41, 'nombre' => 'LR2'],
      ['marca_id' => 41, 'nombre' => 'LR4'],
      ['marca_id' => 41, 'nombre' => 'Defender Ice Edition'],
      ['marca_id' => 41, 'nombre' => 'Range Rover Evoque'],
      ['marca_id' => 42, 'nombre' => 'LS'],
      ['marca_id' => 42, 'nombre' => 'ES'],
      ['marca_id' => 42, 'nombre' => 'SC'],
      ['marca_id' => 42, 'nombre' => 'GS'],
      ['marca_id' => 42, 'nombre' => 'LX'],
      ['marca_id' => 42, 'nombre' => 'RX'],
      ['marca_id' => 42, 'nombre' => 'IS'],
      ['marca_id' => 42, 'nombre' => 'GX'],
      ['marca_id' => 42, 'nombre' => 'RX Hybrid'],
      ['marca_id' => 42, 'nombre' => 'IS-F'],
      ['marca_id' => 42, 'nombre' => 'IS F'],
      ['marca_id' => 42, 'nombre' => 'LS Hybrid'],
      ['marca_id' => 42, 'nombre' => 'HS'],
      ['marca_id' => 42, 'nombre' => 'CT'],
      ['marca_id' => 42, 'nombre' => 'LFA'],
      ['marca_id' => 43, 'nombre' => 'Town Car'],
      ['marca_id' => 43, 'nombre' => 'Continental'],
      ['marca_id' => 43, 'nombre' => 'Mark VII'],
      ['marca_id' => 43, 'nombre' => 'Continental Mark VII'],
      ['marca_id' => 43, 'nombre' => 'Mark VIII'],
      ['marca_id' => 43, 'nombre' => 'Navigator'],
      ['marca_id' => 43, 'nombre' => 'LS'],
      ['marca_id' => 43, 'nombre' => 'Blackwood'],
      ['marca_id' => 43, 'nombre' => 'Aviator'],
      ['marca_id' => 43, 'nombre' => 'Zephyr'],
      ['marca_id' => 43, 'nombre' => 'Mark LT'],
      ['marca_id' => 43, 'nombre' => 'MKX'],
      ['marca_id' => 43, 'nombre' => 'MKZ'],
      ['marca_id' => 43, 'nombre' => 'Navigator L'],
      ['marca_id' => 43, 'nombre' => 'MKS'],
      ['marca_id' => 43, 'nombre' => 'MKT'],
      ['marca_id' => 44, 'nombre' => 'Esprit Turbo'],
      ['marca_id' => 44, 'nombre' => 'Esprit'],
      ['marca_id' => 44, 'nombre' => 'Elan'],
      ['marca_id' => 44, 'nombre' => 'Exige'],
      ['marca_id' => 44, 'nombre' => 'Elise'],
      ['marca_id' => 44, 'nombre' => 'Evora'],
      ['marca_id' => 45, 'nombre' => 'Quattroporte'],
      ['marca_id' => 45, 'nombre' => 'Biturbo'],
      ['marca_id' => 45, 'nombre' => '228'],
      ['marca_id' => 45, 'nombre' => '430'],
      ['marca_id' => 45, 'nombre' => 'Spyder'],
      ['marca_id' => 45, 'nombre' => 'Karif'],
      ['marca_id' => 45, 'nombre' => 'Gran Sport'],
      ['marca_id' => 45, 'nombre' => 'Coupe'],
      ['marca_id' => 45, 'nombre' => 'GranSport'],
      ['marca_id' => 45, 'nombre' => 'GranTurismo'],
      ['marca_id' => 46, 'nombre' => '57'],
      ['marca_id' => 46, 'nombre' => '62'],
      ['marca_id' => 46, 'nombre' => '57S'],
      ['marca_id' => 46, 'nombre' => 'Landaulet'],
      ['marca_id' => 47, 'nombre' => '626'],
      ['marca_id' => 47, 'nombre' => 'RX-7'],
      ['marca_id' => 47, 'nombre' => 'GLC'],
      ['marca_id' => 47, 'nombre' => 'Familia'],
      ['marca_id' => 47, 'nombre' => 'B2000'],
      ['marca_id' => 47, 'nombre' => 'B-Series'],
      ['marca_id' => 47, 'nombre' => '929'],
      ['marca_id' => 47, 'nombre' => 'B2600'],
      ['marca_id' => 47, 'nombre' => 'MX-6'],
      ['marca_id' => 47, 'nombre' => 'MPV'],
      ['marca_id' => 47, 'nombre' => 'MX-5'],
      ['marca_id' => 47, 'nombre' => 'Navajo'],
      ['marca_id' => 47, 'nombre' => '323'],
      ['marca_id' => 47, 'nombre' => 'Protege'],
      ['marca_id' => 47, 'nombre' => 'MX-3'],
      ['marca_id' => 47, 'nombre' => 'B-Series Plus'],
      ['marca_id' => 47, 'nombre' => 'Miata MX-5'],
      ['marca_id' => 47, 'nombre' => 'Millenia'],
      ['marca_id' => 47, 'nombre' => 'B2500'],
      ['marca_id' => 47, 'nombre' => 'Tribute'],
      ['marca_id' => 47, 'nombre' => 'Protege5'],
      ['marca_id' => 47, 'nombre' => 'Mazda6'],
      ['marca_id' => 47, 'nombre' => 'Mazda3'],
      ['marca_id' => 47, 'nombre' => 'RX-8'],
      ['marca_id' => 47, 'nombre' => 'Mazda6 5-Door'],
      ['marca_id' => 47, 'nombre' => 'Mazda5'],
      ['marca_id' => 47, 'nombre' => 'Mazda6 Sport'],
      ['marca_id' => 47, 'nombre' => 'Mazdaspeed6'],
      ['marca_id' => 47, 'nombre' => 'CX-7'],
      ['marca_id' => 47, 'nombre' => 'Mazdaspeed 3'],
      ['marca_id' => 47, 'nombre' => 'CX-9'],
      ['marca_id' => 47, 'nombre' => 'Mazda2'],
      ['marca_id' => 47, 'nombre' => 'CX-5'],
      ['marca_id' => 48, 'nombre' => 'MP4-12C'],
      ['marca_id' => 49, 'nombre' => 'W123'],
      ['marca_id' => 49, 'nombre' => 'W126'],
      ['marca_id' => 49, 'nombre' => 'S-Class'],
      ['marca_id' => 49, 'nombre' => 'E-Class'],
      ['marca_id' => 49, 'nombre' => 'W201'],
      ['marca_id' => 49, 'nombre' => 'SL-Class'],
      ['marca_id' => 49, 'nombre' => '190E'],
      ['marca_id' => 49, 'nombre' => '300CE'],
      ['marca_id' => 49, 'nombre' => '300D'],
      ['marca_id' => 49, 'nombre' => '300E'],
      ['marca_id' => 49, 'nombre' => '300SD'],
      ['marca_id' => 49, 'nombre' => '300SE'],
      ['marca_id' => 49, 'nombre' => '300SL'],
      ['marca_id' => 49, 'nombre' => '300TE'],
      ['marca_id' => 49, 'nombre' => '400E'],
      ['marca_id' => 49, 'nombre' => '400SE'],
      ['marca_id' => 49, 'nombre' => '500E'],
      ['marca_id' => 49, 'nombre' => '500SEL'],
      ['marca_id' => 49, 'nombre' => '500SL'],
      ['marca_id' => 49, 'nombre' => '600SEL'],
      ['marca_id' => 49, 'nombre' => 'C-Class'],
      ['marca_id' => 49, 'nombre' => '400SEL'],
      ['marca_id' => 49, 'nombre' => '500SEC'],
      ['marca_id' => 49, 'nombre' => '600SEC'],
      ['marca_id' => 49, 'nombre' => '600SL'],
      ['marca_id' => 49, 'nombre' => 'SLK-Class'],
      ['marca_id' => 49, 'nombre' => 'M-Class'],
      ['marca_id' => 49, 'nombre' => 'CL-Class'],
      ['marca_id' => 49, 'nombre' => 'CLK-Class'],
      ['marca_id' => 49, 'nombre' => 'G-Class'],
      ['marca_id' => 49, 'nombre' => 'SLR McLaren'],
      ['marca_id' => 49, 'nombre' => 'CLS-Class'],
      ['marca_id' => 49, 'nombre' => 'G55 AMG'],
      ['marca_id' => 49, 'nombre' => 'SL65 AMG'],
      ['marca_id' => 49, 'nombre' => 'R-Class'],
      ['marca_id' => 49, 'nombre' => 'GL-Class'],
      ['marca_id' => 49, 'nombre' => 'SLK55 AMG'],
      ['marca_id' => 49, 'nombre' => 'CL65 AMG'],
      ['marca_id' => 49, 'nombre' => 'Sprinter'],
      ['marca_id' => 49, 'nombre' => 'GLK-Class'],
      ['marca_id' => 49, 'nombre' => 'SLS AMG'],
      ['marca_id' => 49, 'nombre' => 'SLS-Class'],
      ['marca_id' => 49, 'nombre' => 'Sprinter 2500'],
      ['marca_id' => 49, 'nombre' => 'Sprinter 3500'],
      ['marca_id' => 50, 'nombre' => 'Cougar'],
      ['marca_id' => 50, 'nombre' => 'Topaz'],
      ['marca_id' => 50, 'nombre' => 'Grand Marquis'],
      ['marca_id' => 50, 'nombre' => 'Lynx'],
      ['marca_id' => 50, 'nombre' => 'Capri'],
      ['marca_id' => 50, 'nombre' => 'Marquis'],
      ['marca_id' => 50, 'nombre' => 'Sable'],
      ['marca_id' => 50, 'nombre' => 'Tracer'],
      ['marca_id' => 50, 'nombre' => 'Villager'],
      ['marca_id' => 50, 'nombre' => 'Mystique'],
      ['marca_id' => 50, 'nombre' => 'Mountaineer'],
      ['marca_id' => 50, 'nombre' => 'Marauder'],
      ['marca_id' => 50, 'nombre' => 'Monterey'],
      ['marca_id' => 50, 'nombre' => 'Montego'],
      ['marca_id' => 50, 'nombre' => 'Mariner'],
      ['marca_id' => 50, 'nombre' => 'Milan'],
      ['marca_id' => 51, 'nombre' => 'XR4Ti'],
      ['marca_id' => 52, 'nombre' => 'MGB'],
      ['marca_id' => 53, 'nombre' => 'MINI'],
      ['marca_id' => 53, 'nombre' => 'Cooper'],
      ['marca_id' => 53, 'nombre' => 'Clubman'],
      ['marca_id' => 53, 'nombre' => 'Cooper Clubman'],
      ['marca_id' => 53, 'nombre' => 'Countryman'],
      ['marca_id' => 53, 'nombre' => 'Cooper Countryman'],
      ['marca_id' => 54, 'nombre' => 'Space'],
      ['marca_id' => 54, 'nombre' => 'Galant'],
      ['marca_id' => 54, 'nombre' => 'Mirage'],
      ['marca_id' => 54, 'nombre' => 'Starion'],
      ['marca_id' => 54, 'nombre' => 'Pajero'],
      ['marca_id' => 54, 'nombre' => 'Cordia'],
      ['marca_id' => 54, 'nombre' => 'Tredia'],
      ['marca_id' => 54, 'nombre' => 'Truck'],
      ['marca_id' => 54, 'nombre' => 'Chariot'],
      ['marca_id' => 54, 'nombre' => 'Mighty Max'],
      ['marca_id' => 54, 'nombre' => 'Precis'],
      ['marca_id' => 54, 'nombre' => 'Excel'],
      ['marca_id' => 54, 'nombre' => 'L300'],
      ['marca_id' => 54, 'nombre' => 'Sigma'],
      ['marca_id' => 54, 'nombre' => 'Eclipse'],
      ['marca_id' => 54, 'nombre' => 'GTO'],
      ['marca_id' => 54, 'nombre' => 'Diamante'],
      ['marca_id' => 54, 'nombre' => 'RVR'],
      ['marca_id' => 54, 'nombre' => '3000GT'],
      ['marca_id' => 54, 'nombre' => 'Expo'],
      ['marca_id' => 54, 'nombre' => 'Mighty Max Macro'],
      ['marca_id' => 54, 'nombre' => 'Montero'],
      ['marca_id' => 54, 'nombre' => 'Expo LRV'],
      ['marca_id' => 54, 'nombre' => 'Challenger'],
      ['marca_id' => 54, 'nombre' => 'Montero Sport'],
      ['marca_id' => 54, 'nombre' => 'Lancer'],
      ['marca_id' => 54, 'nombre' => 'Lancer Evolution'],
      ['marca_id' => 54, 'nombre' => 'Outlander'],
      ['marca_id' => 54, 'nombre' => 'Endeavor'],
      ['marca_id' => 54, 'nombre' => 'Raider'],
      ['marca_id' => 54, 'nombre' => 'Tundra'],
      ['marca_id' => 54, 'nombre' => 'Outlander Sport'],
      ['marca_id' => 54, 'nombre' => 'i-MiEV'],
      ['marca_id' => 55, 'nombre' => 'Aero 8'],
      ['marca_id' => 56, 'nombre' => '280ZX'],
      ['marca_id' => 56, 'nombre' => 'Maxima'],
      ['marca_id' => 56, 'nombre' => 'Datsun/Nissan Z-car'],
      ['marca_id' => 56, 'nombre' => '300ZX'],
      ['marca_id' => 56, 'nombre' => 'Sentra'],
      ['marca_id' => 56, 'nombre' => '240SX'],
      ['marca_id' => 56, 'nombre' => 'NX'],
      ['marca_id' => 56, 'nombre' => 'Pathfinder'],
      ['marca_id' => 56, 'nombre' => 'Stanza'],
      ['marca_id' => 56, 'nombre' => 'Altima'],
      ['marca_id' => 56, 'nombre' => 'Quest'],
      ['marca_id' => 56, 'nombre' => '200SX'],
      ['marca_id' => 56, 'nombre' => 'Frontier'],
      ['marca_id' => 56, 'nombre' => 'Xterra'],
      ['marca_id' => 56, 'nombre' => '350Z'],
      ['marca_id' => 56, 'nombre' => 'Murano'],
      ['marca_id' => 56, 'nombre' => 'Titan'],
      ['marca_id' => 56, 'nombre' => 'Pathfinder Armada'],
      ['marca_id' => 56, 'nombre' => 'Armada'],
      ['marca_id' => 56, 'nombre' => '350Z Roadster'],
      ['marca_id' => 56, 'nombre' => 'Versa'],
      ['marca_id' => 56, 'nombre' => 'Rogue'],
      ['marca_id' => 56, 'nombre' => 'Cube'],
      ['marca_id' => 56, 'nombre' => 'GT-R'],
      ['marca_id' => 56, 'nombre' => '370Z'],
      ['marca_id' => 56, 'nombre' => 'Leaf'],
      ['marca_id' => 56, 'nombre' => 'JUKE'],
      ['marca_id' => 56, 'nombre' => 'NV1500'],
      ['marca_id' => 56, 'nombre' => 'NV2500'],
      ['marca_id' => 56, 'nombre' => 'NV3500'],
      ['marca_id' => 57, 'nombre' => 'Toronado'],
      ['marca_id' => 57, 'nombre' => '88'],
      ['marca_id' => 57, 'nombre' => '98'],
      ['marca_id' => 57, 'nombre' => 'Achieva'],
      ['marca_id' => 57, 'nombre' => 'Bravada'],
      ['marca_id' => 57, 'nombre' => 'Ciera'],
      ['marca_id' => 57, 'nombre' => 'Custom Cruiser'],
      ['marca_id' => 57, 'nombre' => 'Cutlass Supreme'],
      ['marca_id' => 57, 'nombre' => 'Silhouette'],
      ['marca_id' => 57, 'nombre' => 'Cutlass Cruiser'],
      ['marca_id' => 57, 'nombre' => 'Aurora'],
      ['marca_id' => 57, 'nombre' => 'Cutlass'],
      ['marca_id' => 57, 'nombre' => 'LSS'],
      ['marca_id' => 57, 'nombre' => 'Regency'],
      ['marca_id' => 57, 'nombre' => 'Intrigue'],
      ['marca_id' => 57, 'nombre' => 'Alero'],
      ['marca_id' => 58, 'nombre' => 'Esperante'],
      ['marca_id' => 59, 'nombre' => '207'],
      ['marca_id' => 60, 'nombre' => 'Fury'],
      ['marca_id' => 60, 'nombre' => 'Roadrunner'],
      ['marca_id' => 60, 'nombre' => 'Volare'],
      ['marca_id' => 60, 'nombre' => 'Horizon'],
      ['marca_id' => 60, 'nombre' => 'Reliant'],
      ['marca_id' => 60, 'nombre' => 'Voyager'],
      ['marca_id' => 60, 'nombre' => 'Laser'],
      ['marca_id' => 60, 'nombre' => 'Acclaim'],
      ['marca_id' => 60, 'nombre' => 'Colt'],
      ['marca_id' => 60, 'nombre' => 'Colt Vista'],
      ['marca_id' => 60, 'nombre' => 'Grand Voyager'],
      ['marca_id' => 60, 'nombre' => 'Sundance'],
      ['marca_id' => 60, 'nombre' => 'Neon'],
      ['marca_id' => 60, 'nombre' => 'Breeze'],
      ['marca_id' => 60, 'nombre' => 'Prowler'],
      ['marca_id' => 61, 'nombre' => 'Tempest'],
      ['marca_id' => 61, 'nombre' => 'Grand Prix'],
      ['marca_id' => 61, 'nombre' => 'GTO'],
      ['marca_id' => 61, 'nombre' => 'LeMans'],
      ['marca_id' => 61, 'nombre' => 'Bonneville'],
      ['marca_id' => 61, 'nombre' => 'Firebird'],
      ['marca_id' => 61, 'nombre' => '6000'],
      ['marca_id' => 61, 'nombre' => 'Sunbird'],
      ['marca_id' => 61, 'nombre' => '1000'],
      ['marca_id' => 61, 'nombre' => 'Parisienne'],
      ['marca_id' => 61, 'nombre' => 'Fiero'],
      ['marca_id' => 61, 'nombre' => 'Firefly'],
      ['marca_id' => 61, 'nombre' => 'Grand Am'],
      ['marca_id' => 61, 'nombre' => 'Safari'],
      ['marca_id' => 61, 'nombre' => 'Gemini'],
      ['marca_id' => 61, 'nombre' => 'Firebird Trans Am'],
      ['marca_id' => 61, 'nombre' => 'Chevette'],
      ['marca_id' => 61, 'nombre' => 'Turbo Firefly'],
      ['marca_id' => 61, 'nombre' => 'Trans Sport'],
      ['marca_id' => 61, 'nombre' => 'Grand Prix Turbo'],
      ['marca_id' => 61, 'nombre' => 'Firebird Formula'],
      ['marca_id' => 61, 'nombre' => 'Sunfire'],
      ['marca_id' => 61, 'nombre' => 'Montana'],
      ['marca_id' => 61, 'nombre' => 'Aztek'],
      ['marca_id' => 61, 'nombre' => 'Vibe'],
      ['marca_id' => 61, 'nombre' => 'G6'],
      ['marca_id' => 61, 'nombre' => 'Daewoo Kalos'],
      ['marca_id' => 61, 'nombre' => 'Monterey'],
      ['marca_id' => 61, 'nombre' => 'Montana SV6'],
      ['marca_id' => 61, 'nombre' => 'Torrent'],
      ['marca_id' => 61, 'nombre' => 'Solstice'],
      ['marca_id' => 61, 'nombre' => 'G5'],
      ['marca_id' => 61, 'nombre' => 'G8'],
      ['marca_id' => 61, 'nombre' => 'G3'],
      ['marca_id' => 62, 'nombre' => '914'],
      ['marca_id' => 62, 'nombre' => '944'],
      ['marca_id' => 62, 'nombre' => '911'],
      ['marca_id' => 62, 'nombre' => '928'],
      ['marca_id' => 62, 'nombre' => '924 S'],
      ['marca_id' => 62, 'nombre' => '924'],
      ['marca_id' => 62, 'nombre' => '968'],
      ['marca_id' => 62, 'nombre' => 'Boxster'],
      ['marca_id' => 62, 'nombre' => 'Cayenne'],
      ['marca_id' => 62, 'nombre' => 'Carrera GT'],
      ['marca_id' => 62, 'nombre' => 'Cayman'],
      ['marca_id' => 62, 'nombre' => 'Panamera'],
      ['marca_id' => 63, 'nombre' => '1500'],
      ['marca_id' => 63, 'nombre' => '2500'],
      ['marca_id' => 63, 'nombre' => '3500'],
      ['marca_id' => 63, 'nombre' => 'Dakota'],
      ['marca_id' => 63, 'nombre' => 'C/V'],
      ['marca_id' => 64, 'nombre' => 'Classic'],
      ['marca_id' => 65, 'nombre' => 'Alliance'],
      ['marca_id' => 66, 'nombre' => 'Phantom'],
      ['marca_id' => 66, 'nombre' => 'Ghost'],
      ['marca_id' => 67, 'nombre' => '900'],
      ['marca_id' => 67, 'nombre' => '9000'],
      ['marca_id' => 67, 'nombre' => '9-3'],
      ['marca_id' => 67, 'nombre' => '9-5'],
      ['marca_id' => 67, 'nombre' => '9-7X'],
      ['marca_id' => 67, 'nombre' => '9-2X'],
      ['marca_id' => 67, 'nombre' => '9-4X'],
      ['marca_id' => 68, 'nombre' => 'S-Series'],
      ['marca_id' => 68, 'nombre' => 'L-Series'],
      ['marca_id' => 68, 'nombre' => 'VUE'],
      ['marca_id' => 68, 'nombre' => 'Ion'],
      ['marca_id' => 68, 'nombre' => 'Relay'],
      ['marca_id' => 68, 'nombre' => 'Outlook'],
      ['marca_id' => 68, 'nombre' => 'Aura'],
      ['marca_id' => 68, 'nombre' => 'Sky'],
      ['marca_id' => 68, 'nombre' => 'Astra'],
      ['marca_id' => 69, 'nombre' => 'xA'],
      ['marca_id' => 69, 'nombre' => 'xB'],
      ['marca_id' => 69, 'nombre' => 'tC'],
      ['marca_id' => 69, 'nombre' => 'xD'],
      ['marca_id' => 69, 'nombre' => 'iQ'],
      ['marca_id' => 69, 'nombre' => 'FR-S'],
      ['marca_id' => 70, 'nombre' => 'GT500'],
      ['marca_id' => 70, 'nombre' => 'GT350'],
      ['marca_id' => 71, 'nombre' => 'Fortwo'],
      ['marca_id' => 72, 'nombre' => 'C8 Spyder'],
      ['marca_id' => 72, 'nombre' => 'C8 Spyder Wide Body'],
      ['marca_id' => 72, 'nombre' => 'C8 Laviolette'],
      ['marca_id' => 72, 'nombre' => 'C8 Double 12 S'],
      ['marca_id' => 73, 'nombre' => 'C8'],
      ['marca_id' => 74, 'nombre' => 'Avanti'],
      ['marca_id' => 75, 'nombre' => 'Brat'],
      ['marca_id' => 75, 'nombre' => 'XT'],
      ['marca_id' => 75, 'nombre' => 'Leone'],
      ['marca_id' => 75, 'nombre' => 'Justy'],
      ['marca_id' => 75, 'nombre' => 'Legacy'],
      ['marca_id' => 75, 'nombre' => 'Loyale'],
      ['marca_id' => 75, 'nombre' => 'Alcyone SVX'],
      ['marca_id' => 75, 'nombre' => 'SVX'],
      ['marca_id' => 75, 'nombre' => 'Impreza'],
      ['marca_id' => 75, 'nombre' => 'Forester'],
      ['marca_id' => 75, 'nombre' => 'Outback'],
      ['marca_id' => 75, 'nombre' => 'Outback Sport'],
      ['marca_id' => 75, 'nombre' => 'Baja'],
      ['marca_id' => 75, 'nombre' => 'Tribeca'],
      ['marca_id' => 75, 'nombre' => 'B9 Tribeca'],
      ['marca_id' => 75, 'nombre' => 'Impreza WRX'],
      ['marca_id' => 75, 'nombre' => 'BRZ'],
      ['marca_id' => 76, 'nombre' => 'SJ 410'],
      ['marca_id' => 76, 'nombre' => 'Cultus'],
      ['marca_id' => 76, 'nombre' => 'SJ'],
      ['marca_id' => 76, 'nombre' => 'Swift'],
      ['marca_id' => 76, 'nombre' => 'Sidekick'],
      ['marca_id' => 76, 'nombre' => 'Samurai'],
      ['marca_id' => 76, 'nombre' => 'Esteem'],
      ['marca_id' => 76, 'nombre' => 'X-90'],
      ['marca_id' => 76, 'nombre' => 'Vitara'],
      ['marca_id' => 76, 'nombre' => 'Grand Vitara'],
      ['marca_id' => 76, 'nombre' => 'XL-7'],
      ['marca_id' => 76, 'nombre' => 'Aerio'],
      ['marca_id' => 76, 'nombre' => 'Daewoo Lacetti'],
      ['marca_id' => 76, 'nombre' => 'Daewoo Magnus'],
      ['marca_id' => 76, 'nombre' => 'Forenza'],
      ['marca_id' => 76, 'nombre' => 'Verona'],
      ['marca_id' => 76, 'nombre' => 'Reno'],
      ['marca_id' => 76, 'nombre' => 'XL7'],
      ['marca_id' => 76, 'nombre' => 'SX4'],
      ['marca_id' => 76, 'nombre' => 'Equator'],
      ['marca_id' => 76, 'nombre' => 'Kizashi'],
      ['marca_id' => 77, 'nombre' => 'Roadster'],
      ['marca_id' => 77, 'nombre' => 'Model S'],
      ['marca_id' => 78, 'nombre' => 'Celica'],
      ['marca_id' => 78, 'nombre' => 'MR2'],
      ['marca_id' => 78, 'nombre' => 'Truck Xtracab SR5'],
      ['marca_id' => 78, 'nombre' => 'Previa'],
      ['marca_id' => 78, 'nombre' => 'Camry'],
      ['marca_id' => 78, 'nombre' => '4Runner'],
      ['marca_id' => 78, 'nombre' => 'Corolla'],
      ['marca_id' => 78, 'nombre' => 'Cressida'],
      ['marca_id' => 78, 'nombre' => 'Land Cruiser'],
      ['marca_id' => 78, 'nombre' => 'Paseo'],
      ['marca_id' => 78, 'nombre' => 'Supra'],
      ['marca_id' => 78, 'nombre' => 'Tercel'],
      ['marca_id' => 78, 'nombre' => 'Xtra'],
      ['marca_id' => 78, 'nombre' => 'T100'],
      ['marca_id' => 78, 'nombre' => 'Avalon'],
      ['marca_id' => 78, 'nombre' => 'T100 Xtra'],
      ['marca_id' => 78, 'nombre' => 'Tacoma'],
      ['marca_id' => 78, 'nombre' => 'Tacoma Xtra'],
      ['marca_id' => 78, 'nombre' => 'RAV4'],
      ['marca_id' => 78, 'nombre' => 'Sienna'],
      ['marca_id' => 78, 'nombre' => 'Solara'],
      ['marca_id' => 78, 'nombre' => 'Tundra'],
      ['marca_id' => 78, 'nombre' => 'Ipsum'],
      ['marca_id' => 78, 'nombre' => 'Echo'],
      ['marca_id' => 78, 'nombre' => 'Highlander'],
      ['marca_id' => 78, 'nombre' => 'Prius'],
      ['marca_id' => 78, 'nombre' => 'Sequoia'],
      ['marca_id' => 78, 'nombre' => 'Matrix'],
      ['marca_id' => 78, 'nombre' => 'Yaris'],
      ['marca_id' => 78, 'nombre' => 'Camry Solara'],
      ['marca_id' => 78, 'nombre' => 'Highlander Hybrid'],
      ['marca_id' => 78, 'nombre' => 'Camry Hybrid'],
      ['marca_id' => 78, 'nombre' => 'FJ Cruiser'],
      ['marca_id' => 78, 'nombre' => 'TundraMax'],
      ['marca_id' => 78, 'nombre' => 'Venza'],
      ['marca_id' => 78, 'nombre' => 'Prius v'],
      ['marca_id' => 78, 'nombre' => 'Prius Plug-in Hybrid'],
      ['marca_id' => 78, 'nombre' => 'Prius c'],
      ['marca_id' => 78, 'nombre' => 'Prius Plug-in'],
      ['marca_id' => 79, 'nombre' => 'Beetle'],
      ['marca_id' => 79, 'nombre' => 'Golf'],
      ['marca_id' => 79, 'nombre' => 'Jetta'],
      ['marca_id' => 79, 'nombre' => 'Vanagon'],
      ['marca_id' => 79, 'nombre' => 'Scirocco'],
      ['marca_id' => 79, 'nombre' => 'Quantum'],
      ['marca_id' => 79, 'nombre' => 'GTI'],
      ['marca_id' => 79, 'nombre' => 'Cabriolet'],
      ['marca_id' => 79, 'nombre' => 'Passat'],
      ['marca_id' => 79, 'nombre' => 'Type 2'],
      ['marca_id' => 79, 'nombre' => 'Fox'],
      ['marca_id' => 79, 'nombre' => 'Corrado'],
      ['marca_id' => 79, 'nombre' => 'Eurovan'],
      ['marca_id' => 79, 'nombre' => 'riolet'],
      ['marca_id' => 79, 'nombre' => 'Golf III'],
      ['marca_id' => 79, 'nombre' => 'Jetta III'],
      ['marca_id' => 79, 'nombre' => 'rio'],
      ['marca_id' => 79, 'nombre' => 'New Beetle'],
      ['marca_id' => 79, 'nombre' => 'Touareg'],
      ['marca_id' => 79, 'nombre' => 'R32'],
      ['marca_id' => 79, 'nombre' => 'Phaeton'],
      ['marca_id' => 79, 'nombre' => 'Rabbit'],
      ['marca_id' => 79, 'nombre' => 'Eos'],
      ['marca_id' => 79, 'nombre' => 'GLI'],
      ['marca_id' => 79, 'nombre' => 'Touareg 2'],
      ['marca_id' => 79, 'nombre' => 'CC'],
      ['marca_id' => 79, 'nombre' => 'Tiguan'],
      ['marca_id' => 79, 'nombre' => 'Routan'],
      ['marca_id' => 80, 'nombre' => '240'],
      ['marca_id' => 80, 'nombre' => '740'],
      ['marca_id' => 80, 'nombre' => '940'],
      ['marca_id' => 80, 'nombre' => '960'],
      ['marca_id' => 80, 'nombre' => '850'],
      ['marca_id' => 80, 'nombre' => 'S90'],
      ['marca_id' => 80, 'nombre' => 'V90'],
      ['marca_id' => 80, 'nombre' => 'C70'],
      ['marca_id' => 80, 'nombre' => 'S70'],
      ['marca_id' => 80, 'nombre' => 'V70'],
      ['marca_id' => 80, 'nombre' => 'S80'],
      ['marca_id' => 80, 'nombre' => 'S40'],
      ['marca_id' => 80, 'nombre' => 'V40'],
      ['marca_id' => 80, 'nombre' => 'S60'],
      ['marca_id' => 80, 'nombre' => 'XC90'],
      ['marca_id' => 80, 'nombre' => 'XC70'],
      ['marca_id' => 80, 'nombre' => 'V50'],
      ['marca_id' => 80, 'nombre' => 'C30'],
      ['marca_id' => 80, 'nombre' => 'XC60']
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('modelos_autos')->insert($this->modelos);
    }
}
